src/Server/Local.php
It does the same thing but it gives out a better exception object.
=> Use mustRun instead of run and catch exception

composer.json
=> Requirement should be @ not -

src/Console/WorkerCommand.php, src/Executor/Informer.php, src/Executor/ParallelExecutor.php, src/Executor/SeriesExecutor.php, src/Task/NonFatalException.php, test/src/Executor/InformerTest.php
=> [API] Display non-fatal error on deployment

recipe/common.php
`--depth` create a shallow clone with a history truncated to a limited number of revisions.
=> Shallow clone

phpunit.xml
https://phpunit.de/manual/current/en/textui.html#textui.clioptions
Before:
After:
=> PHPUnit improvements

src/Server/Remote/PhpSecLib.php
=> Fix PhpSecLib integration

src/Server/Remote/PhpSecLib.php
=> Update PhpSecLib::run method to check exit status

composer.lock
This version improves command execution error detection
=> Updated to PHP SSH 1.1.1

recipe/common.php
Fix for Issue #233 on 2.x branch
=> Fix for change to composer installer behind ssl - 2.x branch

recipe/common.php
Fix for Issue #233 on master branch
=> Fix for change to composer installer behind ssl - master

src/functions.php
=> Fixes ask function, was not displaying question

recipe/common.php, test/recipe/CommonTest.php
This is my pull request as discussed in issue #239
=> Improve symlink check in deploy:release task

src/Type/DotArray.php, test/src/Type/DotArrayTest.php
In this Pull Request:
- Update class DotArray:
- implement contructor by `offsetSet()` method.
```php
$d = new DotArray(['abc.xyz' => 1]);
var_dump($d->toArray());
//array (
//  'abc' => 
//  array (
//    'xyz' => 1,
//  ),
//)
```
- change `hasKey()` method for fixed code duplications https://scrutinizer-ci.com/g/deployphp/deployer/indices/829672/duplications/65846246
- Add more test case for class DotArray
=> Update class DotArray and add more test case

recipe/common.php
=> Misleading error message

src/functions.php
…play debug output with this mode
=> Realtime output in runLocally function

src/Console/Output/OutputWatcher.php, src/Executor/Informer.php
About #291 , I tried to use '\r' to move cursor back to line head,and fix it on ubuntu. however it need test for mac.
=> fix issue #291 by add '\r' to output

recipe/symfony.php
https://github.com/deployphp/deployer/issues/310
=> Removed setting the 'auto_migrate' global variable

recipe/common.php
check file by wrong flag in "if"
=> wrong flag

recipe/common.php
=> Add composer options

.editorconfig, .gitignore, .php_cs, README.md, composer.json, recipe/common.php, src/Console/Application.php, src/Deployer.php, src/Executor/Informer.php, src/Executor/ParallelExecutor.php, src/Executor/SeriesExecutor.php, src/Server/Environment.php, src/Server/Remote/PhpSecLib.php, src/Server/Remote/SshExtension.php, src/Stage/StageStrategy.php, src/Task/Task.php, src/Type/DotArray.php, src/Type/Result.php, src/functions.php, test/bootstrap.php, test/src/Console/ApplicationTest.php, test/src/Console/Output/OutputWatcherTest.php, test/src/Console/TaskCommandTest.php, test/src/DeployerTest.php, test/src/Executor/InformerTest.php, test/src/Executor/ParallelExecutorTest.php, test/src/Executor/SeriesExecutorTest.php, test/src/Helper/DeployerHelper.php, test/src/Type/DotArrayTest.php
- Updated reamde
- Added an editoconfig file and php_cs file
- formatted code - very few code changes (mainly spaces and blank lines)
=> Switch to PSR-2

.styleci.yml
So that we can use https://styleci.io
=> Add StyleCI settings

bin/dep
Also apply PSR-2 fixes to bin/dep
=> Also apply PSR-2 fixes to bin/dep

README.md
Also add shell syntax highlighting as for https://github.com/deployphp/docs/pull/31
=> Add curl command

composer.json
Add the following details :
- homepage
- support
=> Add homepage and support section to composer.json

README.md
=> Prefix build command with dot and slash

recipe/common.php
=> Syntax - indentation

src/Server/Remote/SshExtension.php
In this PR:
* add support forward agent feature when using `ext-ssh2`
=> add support forward agent feature when using ext-ssh2

src/Server/Builder.php, src/Server/Configuration.php, src/functions.php
Corrected comments
Refactored default setting into builder class to match other defaults location
=> Added ability to enable ssh config via serverList yaml functionality.

recipe/common.php
Change to recursive chmod to avoid inconsistency permission in nested dirs
=> Change to recursive chmod

recipe/magento.php
=> Magento recipe

recipe/common.php
see #206 
If you agree this change i update doc, tests and rebase
=> WIP/POC - copy directories

recipe/drupal8.php
=> Added basic drupal 8 recipe

recipe/cakephp.php
Would be nice to have this recipe added as an example to the CakePHP folks using the library.
Great work by the way!
=> Add CakePHP 3 recipe

test/recipe/RemoteServerTest.php
| Fixed tickets | #490 
This PR fixed Travis CI build fails follow @MaartenStaa suggestion in #490
=> Fixed Travis CI build fails follow @MaartenStaa suggestion

recipe/common.php
=> Tweaked another couple spelling mistakes

recipe/laravel.php
As per https://laravel.com/docs/5.2#configuration
Q | A
------------ | -------------
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Fixed tickets | -
=> Updated writable dirs

recipe/symfony3.php
=> Add Symfony3 recipe

recipe/common.php
=> Fix #533 shared_files directory handling

recipe/common.php
Now we can specify a path for the composer command, avoiding the download
Q | A
------------ | -------------
Bug fix? | no
New feature? | yes
BC breaks? | no
Deprecations? | no
Fixed tickets | -
=> Added variable for composer command path

recipe/drupal7.php
| Fixed tickets | n/a
Fixed typo errors of inline comments for Drupal 7 recipe.
=> Fixed typo errors of inline comments for Drupal 7 recipe.

src/Server/Remote/PhpSecLib.php, src/Server/Remote/SshExtension.php
=> Fixes #257

recipe/common.php
=> fix #558: check releases_list to contain only releases

recipe/common.php
Add some comments to make clear why the checks of the access-rights are
defined in such a complex structure.
=> Add comments to describe access-right settings

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This PR is to make other PR has above Q&A table as default.
Ref: [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates) feature.
=> Pull request template

recipe/common.php, test/recipe/CommonTest.php
| Q                    | A
| -------------------| ---
| Bug fix?          | no
| BC breaks?     | no
| Fixed tickets    | -
As comment in PR #453, in this PR:
* Added task to clean up files and/or directories
=> Adding a task to clean files and/or directories

src/Executor/Informer.php, test/src/Executor/InformerTest.php
=> Task duration

recipe/common.php
Re-submission of #583, but instead of enforcing the removal of this directory we'll now throw an exception.
=> Adds check for existing /current directory to deploy:prepare

.php_cs
Add header comment fixer to `.php_cs` file
=> Add header comment fixer

.gitattributes
Some files and folders shall not be exported by `git-archive`
=> Do not export some files and folders

recipe/common.php
| Fixed tickets | #649
~~This PR have a BC break~~
**The BC break is reverted**
=> Fixed bug #649

src/Bootstrap/BootstrapByConfigFile.php, src/Cluster/Cluster.php, src/Cluster/ClusterBuilder.php, src/Cluster/ClusterFactory.php, src/Cluster/ClusterInterface.php, src/Cluster/Node.php, src/Cluster/NodeInterface.php, src/functions.php, test/fixture/servers.yml, test/src/Bootstrap/BootstrapByConfigFileTest.php, test/src/Cluster/ClusterFactoryTest.php, test/src/Cluster/NodeTest.php, test/src/FunctionsTest.php
I added cluster feature that allows you to deploy
a bunch of servers, please see below example.
You can define unlimited servers in the array,
please keep in mind that all the servers are
gonna use same auth method/password/key.
cluster('my_istanbul_dc_cluster', ['192.168.0.1','192.168.0.2','192.168.0.3'], 22)
->user('server_user')
->password('my123passwd')
->forwardAgent()
->stage('production')
->env('deploy_path', '/your/project/path');
You can check ClusterBuilder class to see other supported methods.
| Fixed tickets |
=> Cluster - feature

README.md
=> Shorten deployer.phar curl download command

recipe/common.php
=> Fix issue 675

composer.lock
=> Updated PHPSecLib from 2.0.1 to 2.0.2

recipe/common.php
| Fixed tickets | 765
deployphp/deployer/issues/765
deployphp/deployer/pull/766
=> 4.x: changes flag order for chmod to work on bsd

recipe/common.php
| Fixed tickets | 765
deployphp/deployer/issues/765
=> changes flag order for chmod to work on bsd

src/Bootstrap/BootstrapByConfigFile.php, src/Builder/BuilderInterface.php, src/Cluster/Cluster.php, src/Cluster/ClusterBuilder.php, src/Cluster/ClusterFactory.php, src/Cluster/Node.php, src/Server/Builder.php, src/Server/Configuration.php, src/Task/Scenario/GroupScenario.php, src/Task/Task.php, src/functions.php, test/src/Bootstrap/BootstrapByConfigFileTest.php
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | No |
| BC breaks? | No |
| Deprecations? | No |
| Fixed tickets | N/A |
I've fixed last minor bugrisk issue from [SensioLabs Insight](https://insight.sensiolabs.com/projects/69072898-df4a-4dee-ab05-c2ae83d6c469/analyses/533), fixed some minor coding standard, doc block, typehinting issues and removed unnecessary use statements (with classes from current namespace).
=> Fix coding standards, doc blocks and typehinting

test/docker/Dockerfile, test/docker/README.md, test/docker/docker-bootstrap.sh, test/docker/run.sh
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | yes |
| Fixed tickets | none |
Since deployer's unit tests need at least an open SSHd running on the system, I thought that it might be nice to have reproducible builds inside a docker container. Let me know if this is something you would want to merge, so I can add some polish :smile:
=> [WIP] Docker test runner

src/functions.php
=> shortcut of parse function

recipe/silverstripe.php
=> added namespace to silverstripe recipe to make it work

recipe/typo3.php
=> added namespace to typo3 recipe to make it work in 4.0

recipe/common.php
| BC breaks?    | Don't know. Please check.
| Fixed tickets | #875
=> Copy instead creating new

UPGRADE.md
UPGRADE.md mention of need to manually purge old 3.x releases
=> Upgrade note regarding need to manually remove old 3.x releases

recipe/laravel.php
It clears all compiled views from the respective shared dir.
=> Add artisan:view:clear command to laravel recipe

.styleci.yml, CONTRIBUTING.md, README.md, UPGRADE.md, build, recipe/README.md, src/Bootstrap/BootstrapByConfigFile.php, src/Cluster/Cluster.php, src/Cluster/Node.php, src/Console/Application.php, src/Console/Output/OutputWatcher.php, src/Executor/ParallelExecutor.php, src/Initializer/Template/SymfonyTemplate.php, src/Task/Context.php, test/fixture/servers.yml, test/src/Bootstrap/BootstrapByConfigFileTest.php, test/src/Cluster/ClusterFactoryTest.php, test/src/Console/ApplicationTest.php, test/src/Console/Output/OutputWatcherTest.php, test/src/DeployerTest.php, test/src/FunctionsTest.php, test/src/Task/ContextTest.php
| Fixed tickets | #915 
Just making sure that there are not trailing whitespaces. Also added configuration to travis in order to check for that.
Wasn't sure about creating another PR for #915.
=> Remove trailing whitespaces and improve UPGRADE.md

src/Executor/ParallelExecutor.php
Backporting fix from 4.0
See https://github.com/deployphp/deployer/commit/3e40fcd958e2ac6eeb292fe1911f652803fe50db#diff-ecc506bcfd58cb6526cd2db33d5121cdR195
=> CN-411 Fix exit code for parallel execution

src/functions.php
This mirrors the run/runLocally functions.
=> Add "testLocally" function

bin/dep
=> Prevent leak of variables into deploy.php

composer.json, composer.lock
---
This PR ensures that required dependencies are and will always be sorted.
=> Sort dependencies.

CHANGELOG.md, recipe/deploy/shared.php, test/recipe/CommonTest.php
`Can not share same dirs` bug fix.
| Fixed tickets | #995
=> Fix sharing folders having similar names

recipe/common.php
=> use bin/php when composer is found

CHANGELOG.md, bin/dep, composer.json
=> Autoload functions via Composer

CHANGELOG.md, src/Server/Remote/NativeSsh.php
=> Fix uploading files with spaces in a path via Native SSH

src/Server/Builder.php, src/Server/Configuration.php, src/Server/Remote/PhpSecLib.php, src/Server/Remote/SshExtension.php
Just fixes of Scrutinizer issues.
=> Refactor code according to Scrutinizer recommendations

src/Console/InitCommand.php, src/Util/Reporter.php
=> Fix some issues from SensioLabsInsight

CHANGELOG.md, src/Server/Environment.php, test/src/Server/EnvironmentTest.php
=> Parse hyphens in environment setting names

CHANGELOG.md, src/functions.php
=> Support for multiple choice questions

src/Console/WorkerCommand.php
=> Fix missing setHidden method

README.md
Updated the README.md to reflect, that Goratsch Webdesign is using Deployer as the deployment tool of choice.
Keep up with the great work you are doing! :)
=> Added Goratsch Webdesign as a user of Deployer

CHANGELOG.md, recipe/deploy/lock.php
Prefix launcher script and append current stage.
=> Improve lock message

test/src/Host/HostTest.php
| Fixed tickets | #1156
This updates the tests as well.
=> Add port if specified to ssh options.

CHANGELOG.md, src/functions.php
=> Fixes upload / download with optional rsync ssh option #1227

CHANGELOG.md, recipe/magento2.php
This removes maintenance mode after failure, in case it fails during the DB upgrade.
=> Disable maintenance after failure

CHANGELOG.md, KNOWN_BUGS.md, src/Ssh/Client.php
=> Fix bug with ssh multiplexing initialization

CHANGELOG.md, recipe/symfony.php
See:
http://symfony.com/doc/current/deployment.html#d-clear-your-symfony-cache
=> Cache must be cleared before it's warmed up (Symfony recipe)

CHANGELOG.md, src/Deployer.php
=> Added possibility to use callable when setting 'default_stage'.

CHANGELOG.md, src/Console/InitCommand.php, src/Initializer/Template/Typo3Template.php
=> Add TYPO3 project type to dep init

.styleci.yml
=> Remove useless else

recipe/deploy/update_code.php
=> Make branch less delicious

CHANGELOG.md
=> Updates CHANGELOG.md for #1364

CHANGELOG.md, recipe/symfony.php
See #718
| Fixed tickets | #718
=> Fix time format for touch when deploying assets

CHANGELOG.md, recipe/config/hosts.php
=> Fixed bug when config:hosts shows more than one table of hosts #1403

.travis.yml
> * Add description under added/changed/fixed section.
> * Add reference to closed issues `[#000]`.
> * Add link to issue in the end of document.
I guess such a change shouldnt be noted in the changelog, should it?
=> Added php 7.2 to travis builds

src/Utility/ProcessOutputPrinter.php
just adding some docs. I guess this doesnt need a changelog entry?
=> added phpdocs for ProcessOutputPrinter->callback()

src/Deployer.php
=> document "pop" container property

src/Deployer.php, src/functions.php
=> added phpdocs

CHANGELOG.md, recipe/deploy/vendors.php
=> Missing {{bin/php}} in deploy:vendors

CHANGELOG.md, src/functions.php
| Fixed tickets | Closes #1480
Before this Change
After this Change
=> throw meaningfull exception on errors in cd()

src/functions.php
fixed typo introduced in https://github.com/deployphp/deployer/commit/722b6936882a89051a4145ef1feeffe682934ac2
=> fixed typo

src/functions.php
cosmetics: make code more local. reduce number of required DI calls.
(I guess such changes do not require changelog entries?)
=> create objects only when necessary

CHANGELOG.md, recipe/deploy/vendors.php
Reverts deployphp/deployer#1521
=> Revert "Missing {{bin/php}} in deploy:vendors"

src/Utility/ProcessRunner.php
just adding docs, escpecially for the Exception case which you might want to handle on invalid run() commands.
intentionally without a CHANGELOG.md as it seems not required.
=> added phpdoc to ProcessRunnter->run()

CHANGELOG.md, recipe/deploy/writable.php
=> Improve readability of command for finding web server user

CHANGELOG.md, composer.json, composer.lock
=> Update symfony package dependencies to 4.0

recipe/symfony4.php
Default Symfony 4 recipe should provide cache clear & warmup task - eg. used for auto generated doctrine proxy class.
=> [Symfony recipe] Add cache clear & warmup

CHANGELOG.md, recipe/deploy/writable.php
=> modify wrong ticket url

CHANGELOG.md, recipe/deploy/cleanup.php
> * Add description under added/changed/fixed section.
> * Add reference to closed issues `[#000]`.
> * Add link to issue in the end of document.
Forgot to add options in #1607 to all paths.
=> Added cleanup_use_sudo option to all commands in deploy:cleanup

src/Host/Host.php
=> Fix return types for fluent interface

recipe/laravel.php
=> Laravel Task artisan:migrate should only run once.

composer.lock
Update the `composer.lock` following the latest changes.
=> Update Composer lock

test/src/FunctionsTest.php
=> remove undefined class usage

src/Collection/Collection.php, src/Collection/CollectionInterface.php, src/Collection/PersistentCollection.php, src/Configuration/Configuration.php, src/Configuration/ConfigurationAccessor.php, src/Exception/ConfigurationException.php, src/Exception/Exception.php, src/Exception/GracefulShutdownException.php, src/Exception/InitializationException.php, src/Exception/NonFatalException.php, src/Exception/RuntimeException.php, src/Executor/ExecutorInterface.php, src/Executor/ParallelExecutor.php, src/Executor/SeriesExecutor.php
=> [Collection], [Configuration], [Exception], [Executor] upgrade code to php7

.gitignore, CHANGELOG.md
I updated .gitignore.
- added coverage.xml in case `phpunit --coverage-clover=coverage.xml` is executed
- removed .php_cs.cache, because this project use styleci now
- added .DS_Store for macOS developpers
=> Updated gitignore

.travis.yml
| Fixed tickets | #1728 
I want to resolve #1728 . 
- using composer cache on Travis CI.
- using container on Travis CI.
=> Speedup Travis CI

README.md
This simple PR updates two images links to HTTPS.
| Fixed tickets | No
=> Updating shields to HTTPS

src/Task/Task.php
Return self in addBefore and addAfter methods to follow builder pattern
=> Return self in addBefore and addAfter methods to follow builder pattern

CHANGELOG.md, recipe/sulu2.php
=> Added recipe for sulu 2.0

CHANGELOG.md, recipe/flow_framework.php
=> Add lock/unlock to deploy task

recipe/common.php
=> Added key to disable the display of package suggestions

CHANGELOG.md, bin/dep
| Fixed tickets | #1842
CHANGELOG is updated and the #1842 issue will be closed after this PR is merged.
=> Fix deployer detects wrong version

CHANGELOG.md, recipe/deploy/writable.php
=> Avoid zombie processes in http user resolution.

src/Host/FileLoader.php
=> Fix typo in error message

docs/how-to-deploy-laravel.md
=> Grammatical and Spelling Changes

CHANGELOG.md, recipe/deploy/shared.php, test/fixture/recipe/deploy.php, test/fixture/repository/app/config/parameters_dev.yml, test/fixture/repository/app/config/parameters_prod.yml, test/recipe/DeployTest.php
Reverts deployphp/deployer#1895
=> Revert "Handle asterisk wildcard in shared files"

CHANGELOG.md, docs/examples/simple-deploy.md
I have just started with Deployer and find it to be very powerful but lacking in a "big picture" overview of how it can be used. So now that I've figured out my own Deployer script and how to implement it, I thought I'd write up this little documentation page to share with others and hopefully save them some of the time and frustration I had to deal with. ;-)
>
>
>
=> Sample real-world deployment script

docs/examples/simple-deploy.md
2 lines were missing from this script. Here they are.
| Bug fix?      |  No
=> added missing lines to get latest releases

src/Ssh/Arguments.php
| Fixed tickets | #1356 
See #1356 for more info.
=> Fixing "Too long for Unix domain socket" error deployphp/deployer#1356

src/Ssh/Arguments.php
| Fixed tickets | #1356 
Removing some redundant attempts at creating correct length of controlPath.
=> Removing redundant controlPath attempts

recipe/deploy/check_remote.php, recipe/deploy/cleanup.php, recipe/deploy/clear_paths.php
Add minor fixes for `recipes/deploy` files.
=> Add minor fixes for recipes steps

CHANGELOG.md, composer.json, composer.lock
Add Symfony 5 Support
#SymfonyHackday
=> Add Symfony 5 support #SymfonyHackday

CHANGELOG.md, docs/configuration.md
=> Add `default_timeout` to configuration example

CHANGELOG.md, recipe/config/current.php, recipe/config/hosts.php
=> Filter output upon stage argument only when defined for host fixes #1909

CHANGELOG.md, recipe/joomla.php
=> Added recipe for Joomla!

README.md
=> Add missing Top Supporter

CHANGELOG.md, recipe/symfony.php
=> Composer options debug based on sf env

CHANGELOG.md, recipe/contao.php
This is the follow-up PR of #1906.
=> Add a configuration file for Contao

docs/getting-started.md
The sample code doesn't work if the set('default_stage', '...') is not set.
=> Minor fix for getting started.

recipe/shopware6.php
Due to the lack of ANY shopware6 installation routine, here's my little beginning of it. If you think it can be made better, I am very happy to have your ideas on board of this.
=> Shopware6 installation routine

recipe/shopware6.php
Corrections made for smoother workflow. Tutorial on how to work with this receipe comming soon!
| Bug fix?      | Yes or No
| New feature?  | Yes or No
| BC breaks?    | Yes or No
| Deprecations? | Yes or No
=> Process corrected

CHANGELOG.md, contrib/ispmanager.php, docs/advanced/ispmanager.md
ISPManager recipe with docs and examples
=> Ispmanager recipe

recipe/shopware6.php
I've made changes done in https://github.com/deployphp/deployer/pull/2098 in this pull request so the original author doesn't have to fix the merge conflicts, as asked in https://github.com/deployphp/deployer/pull/2098#issuecomment-664496073
=> Updated shared_dirs list, added assets install task for Shopware 6

docs/api.md
Searching through the api reference drove me nuts, I really had to sort the listing. 😄
Maybe I even add some outline in the future. 😌 
(Plus I fixed some [markdownlint](https://github.com/DavidAnson/markdownlint) errors)
=> sort api reference headings

CHANGELOG.md, recipe/symfony5.php
=> Symfony 5 recipe

recipe/shopware6.php
I was confused by production/development template terminology so I where I previously changed the recipe to work with the development template (which was wrong), I now fixed it to work with the production template
More info; https://www.p16r.nl/2020-08-28-shopware-6-development-versus-production-template/
=> Updated Shopware 6 recipe to reflect production template

.travis.yml, composer.lock
=> Enhancement: Validate composer.json and composer.lock

docs/hosts.md
Add `branch` param after issue #1946 FIXED
=> Update params avalaible in hosts.yml

CHANGELOG.md
Added missing entry about change introduced as a part of fix for the issue #2178.
Sorry, didn't notice that the `CHANGELOG.md` wasn't staged for commit.
=> [issue-2178] updated CHANGELOG.md

CHANGELOG.md, contrib/hangouts.php
=> feat!: adapt chat notify favicon to handle custom links

.github/workflows/test.yml, CHANGELOG.md, recipe/deploy/vendors.php, recipe/symfony.php
> You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
=> [composer 3] Removed deprecated option "--no-suggest"

CHANGELOG.md, phpcs.xml.dist, src/functions.php
As mentioned in #2187 the adding of type declarations can improve the quality of code. I added as far as I could in the src/functions.php file.
=> Typehint functions file

src/functions.php
>      Please, update CHANGELOG.md by running next command:
>      $ php bin/changelog
not sure whether doc only changes should be noted in the CHANGELOG?
=> updated docs for fail()

src/Task/Task.php
Doctypes only change.. for better IDE autocompletion
=> fix phpdocs

.github/workflows/docs.yml, recipe/deploy/vendors.php
=> Add docgen check action

phpcs.xml, src/Collection/Collection.php, src/Configuration/Configuration.php, src/Host/HostCollection.php, src/Task/TaskCollection.php
Refactored the code in `src/Collection` to include type declarations for method arguments and returned values.
Also updated the code in `src/Configuration/Configuration.php` to add missing type declaration for `ownValues`
=> [issue-2187] Type declarations for src/Collection

phpcs.xml, src/Task/Context.php, src/Task/GroupTask.php, src/Task/ScriptManager.php, src/Task/Task.php, src/Task/TaskCollection.php
Added type declarations to methods that belong to classed defined in the `\Deployer\Task` namespace
=> [#2187] Added type declarations to src/Task classes

CHANGELOG.md, composer.json, composer.lock, phpstan.neon, src/Command/RunCommand.php, src/Command/TreeCommand.php, src/Component/PharUpdate/Console/Command.php, src/Component/PharUpdate/Exception/Exception.php, src/Component/PharUpdate/Manifest.php, src/Component/ProcessRunner/Printer.php, test/phpstan-baseline.neon
- fixed phpstan level 1 warnings
- increase phpstan level, to improve tool coverage
=> fix phpstan level 1 warnings

CHANGELOG.md, phpstan.neon, src/Component/PharUpdate/Manifest.php, src/Component/PharUpdate/Version/Builder.php, src/Support/Changelog/ParseException.php, src/functions.php, test/phpstan-baseline.neon
=> fix phpstan level 2 warnings

phpstan.neon, src/Component/PharUpdate/Update.php, src/Support/Changelog/ParseException.php, test/phpstan-baseline.neon
as you removed the changelog items of phpstan level 1/2, I did intentionally not add a new changelog item
=> fix phpstan level 3 warnings

phpcs.xml, src/Utility/Httpie.php, src/Utility/Rsync.php
=> added type declarations for src/Utility

phpcs.xml, src/Logger/Handler/FileHandler.php, src/Logger/Handler/HandlerInterface.php, src/Logger/Handler/NullHandler.php, src/Logger/Logger.php
=> added type declarations for src/Logger

phpcs.xml, src/Host/Host.php, src/Host/HostCollection.php, src/Host/Localhost.php, src/Host/Range.php
=> added type declarations for src/Host

phpcs.xml, src/Executor/Master.php, src/Executor/Messenger.php, src/Executor/Planner.php, src/Executor/Server.php, src/Executor/Worker.php
=> added type declarations for src/Executor

phpcs.xml, src/Exception/Exception.php
=> added type declarations for src/Exception

phpcs.xml, src/Component/PharUpdate/Console/Command.php, src/Component/PharUpdate/Console/Helper.php, src/Component/PharUpdate/Exception/Exception.php, src/Component/PharUpdate/Exception/ExceptionInterface.php, src/Component/PharUpdate/Exception/FileException.php, src/Component/PharUpdate/Exception/InvalidArgumentException.php, src/Component/PharUpdate/Exception/LogicException.php, src/Component/PharUpdate/Manager.php, src/Component/PharUpdate/Manifest.php, src/Component/PharUpdate/Update.php, src/Component/PharUpdate/Version/Builder.php, src/Component/PharUpdate/Version/Comparator.php, src/Component/PharUpdate/Version/Dumper.php, src/Component/PharUpdate/Version/Exception/InvalidIdentifierException.php, src/Component/PharUpdate/Version/Exception/InvalidNumberException.php, src/Component/PharUpdate/Version/Exception/InvalidStringRepresentationException.php, src/Component/PharUpdate/Version/Exception/VersionException.php, src/Component/PharUpdate/Version/Parser.php, src/Component/PharUpdate/Version/Validator.php, src/Component/PharUpdate/Version/Version.php, src/Component/ProcessRunner/Printer.php, src/Component/ProcessRunner/ProcessRunner.php, src/Component/Ssh/Client.php
=> added type declarations for src/Component

CHANGELOG.md, docs/recipe/codeigniter.md, docs/recipe/flow_framework.md, docs/recipe/fuelphp.md, docs/recipe/joomla.md, docs/recipe/magento.md, docs/recipe/prestashop.md, docs/recipe/shopware.md, docs/recipe/silverstripe.md, docs/recipe/sulu.md, docs/recipe/typo3.md, docs/recipe/wordpress.md, docs/recipe/yii.md, docs/recipe/zend_framework.md, src/Documentation/ApiGen.php, src/Documentation/DocGen.php, src/Documentation/DocRecipe.php
closes https://github.com/deployphp/deployer/issues/2253
=> fix bin/docgen on windows

CHANGELOG.md, contrib/rabbit.php
=> fixed typo in rabbit recipe

phpstan.neon, src/Component/PharUpdate/Version/Validator.php, src/functions.php, test/phpstan-baseline.neon
like in previous PRs with the same topic, this changes don't have a CHANGELOG.md line. this was your prefered way to handle this in the past.
=> fix phpstan level 4 warnings

phpcs.xml, src/Command/AutocompleteCommand.php, src/Command/CommandCommon.php, src/Command/ConfigCommand.php, src/Command/ConnectCommand.php, src/Command/CustomOption.php, src/Command/DiceCommand.php, src/Command/InitCommand.php, src/Command/MainCommand.php, src/Command/RunCommand.php, src/Command/SelectCommand.php, src/Command/SshCommand.php, src/Command/TreeCommand.php, src/Command/WorkerCommand.php, src/Deployer.php, src/Importer/Importer.php, src/Selector/Selector.php, src/Support/Changelog/Changelog.php, src/Support/Changelog/Item.php, src/Support/Changelog/ParseException.php, src/Support/Changelog/Parser.php, src/Support/Changelog/Version.php, src/Support/Csv.php, src/Support/ObjectProxy.php, src/Support/Reporter.php, src/Support/Stringify.php, src/Support/helpers.php
=> Add missing types

CHANGELOG.md, src/functions.php
Sorry can't figure out how to write and run tests. It's 3am now.
=> Fix impossibility to set empty password via askHiddenResponse()

docs/recipe/magento2.md, recipe/magento2.php
=> Sync content_version for magento assets between hosts.

CHANGELOG.md, docs/api.md, src/Documentation/ApiGen.php, src/functions.php, test/joy/NamedArgumentsTest.php, test/joy/recipe/named_arguments.php
=> Add named arguments to run and runLocally

docs/recipe/magento2.md, recipe/magento2.php
=> Fix formatting

src/Selector/Selector.php, test/src/Selector/SelectorTest.php
Fix for https://github.com/deployphp/deployer/issues/2439
=> Make selector accept array values

src/Selector/Selector.php, src/Task/GroupTask.php, test/src/Task/TaskTest.php
=> Fix execution of group tasks via invoke()

src/Command/SelectCommand.php, src/Component/ProcessRunner/Printer.php, src/Executor/Master.php, src/Executor/Messenger.php, src/Executor/Planner.php, src/Executor/Worker.php, src/Host/Host.php, src/Task/Context.php, src/Utility/Rsync.php, src/functions.php, tests/bootstrap.php
=> Fix local tasks

docs/recipe/deploy/update_code.md, recipe/deploy/release.php, recipe/deploy/status.php, recipe/deploy/update_code.php, src/Support/Config/verification.php
=> Refactor deploy:update_code

src/Command/ConfigCommand.php, src/Command/InitCommand.php, src/Command/RunCommand.php, src/Command/SshCommand.php, src/Command/TreeCommand.php, src/Command/WorkerCommand.php, src/Component/PharUpdate/Console/Helper.php, src/Configuration/Configuration.php, src/Deployer.php, src/Documentation/DocGen.php, src/Documentation/DocRecipe.php, src/Documentation/DocTask.php, src/Exception/TimeoutException.php, src/Executor/Master.php, src/Executor/Planner.php, src/Logger/Logger.php, src/Support/Stringify.php, tests/src/Component/Pimple/PimpleTest.php, tests/src/DeployerTest.php, tests/src/FunctionsTest.php, tests/src/Task/ScriptManagerTest.php
Ensure single empty line above and below use block
=> Remove Unused use Statements

contrib/npm.php, docs/KNOWN_BUGS.md, docs/cli.md, docs/contrib/npm.md, docs/getting-started.md, docs/installation.md
=> Standardize Markdown Code Block Syntax

CHANGELOG.md
=> Update CHANGELOG for artisan changes

CHANGELOG.md, src/Component/Ssh/Client.php
=> #2503: TypeError, port is int on escapeshellarg

CHANGELOG.md, recipe/symfony.php
=> Fix .env for Symfony recipe

src/Utility/Rsync.php, src/functions.php
Eases consumption of this package from custom recipies
=> upload(): add more precise phpdocs

CHANGELOG.md, recipe/deploy/update_code.php
Changed the way the GIT remote URL is fetched from the config.
=> Update GIT remote origin

CHANGELOG.md, contrib/slack.php, docs/contrib/slack.md
=> Fixes #2525

recipe/cakephp.php
I don't think we need anything else to fix this typo.
=> Fixes #2574

docs/UPGRADE.md
=> Add example for deploy script after upgrade

contrib/slack.php
=> added error checking on Slack response

CHANGELOG.md, recipe/deploy/update_code.php
=> Add Port When Running SSH Keyscan

recipe/deploy/release.php
Reverts deployphp/deployer#2626
=> Revert "Use `cleanup_use_sudo` in task `deploy:release`"

recipe/deploy/writable.php
=> Silence superfluous chgrp errors

CHANGELOG.md, recipe/deploy/release.php, recipe/deploy/update_code.php
=> Use build in php-function to detect scheme, hostname and port in repo url

contrib/cloudflare.php, docs/contrib/cloudflare.md
- Fix cloudflare response handling
- Add optional Zone ID variable + update readme
=> Fix Cloudflare Response

recipe/pimcore.php
=> [Pimcore] bin/php is included in bin/console already

recipe/deploy/update_code.php
=> Fix minor typos in comments

recipe/shopware.php
=> #2760 Do not run deployment if no current path exists

.github/workflows/test.yml, src/Collection/Collection.php, src/Component/Pimple/Container.php, src/Configuration/Configuration.php, src/Executor/Master.php
To suppress the error for the following files I added ReturnTypeWillChange attributes. The same for the Symfony https://github.com/symfony/symfony/pull/41495 
This PR will have a support for PHP8.1
=> Draft: [PHP8.1] Add ReturnTypeWillChange attributes where necessary.

docs/recipe/provision.md, recipe/provision.php, recipe/provision/databases.php
In addition, increase timeout of `mysql-server` install
=> Add missing provisioning of databases in provision recipe

docs/recipe/provision/databases.md, recipe/provision/databases.php
=> Add provision of mariadb

docs/ci-cd.md
Sorry :smile: but I only noticed after you merged PR #2777
=> [Docs] GitLab CI/CD - Fix formatting

contrib/sentry.php
Sentry does not work properly with the new `update_code_strategy`, this fixes it to work with both
=> Sentry fix for new update_code strategies

docs/UPGRADE.md
=> Add a note about multiple host with different release number

contrib/cachetool.php, docs/contrib/cachetool.md
=> Fix cachetool PHP 7 compatibility, fixes #2836

docs/installation.md
@campaignupgrade works this for you?
=> Fixes #1305

contrib/rsync.php
=> Remove not longer existing cleanup task

recipe/deploy/writable.php
This fixes #2850.
I removed the `catch` block completely, because it is untypical (all other calls of `run` do not have one) and the message can be misguiding (`$sudo`).
=> Fix for #2850

recipe/magento2.php
=> Fix Magento version detection, fixes #2905

bin/dep
=> [#2912] Fix the dep init in PHP 8.1

src/Command/AutocompleteCommand.php
=> zsh completion syntax fix

src/Utility/Httpie.php
Hello.
I've quickly added PATCH method to Httpie.
I need this to update messages in webhooks integrations (discord).
I currently respected the existing scheme, but i do think it would be better to allow more (any) methods by some refactoring.
Still i'd rather have it discussed here upfront before going further.
=> Adding PATCH to Httpie

contrib/ispmanager.php, contrib/workplace.php, docs/api.md, recipe/silverstripe.php, src/Task/Task.php, src/functions.php
=> Task: added phpdocs

.github/dependabot.yml
This PR adds a [configuration file for Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#about-the-dependabotyml-file) to ease the maintenance of the project.
=> Configuration file for Dependabot

recipe/deploy/vendors.php
Not sure if this is correct but otherwise, the wrong PHP binary will be used.
=> Make sure to use the correct PHP binary with existing Composer

contrib/php-fpm.php
Use {{bin/php}} and add statement terminator for php_fpm_version.
=> Add statement terminator in php_fpm_version

src/functions.php
Reverts deployphp/deployer#2951
=> Revert "Check func_num_args() in get()"

composer.json, composer.lock, src/Command/BlackjackCommand.php, src/Command/MainCommand.php, src/Component/PharUpdate/Console/Helper.php, src/Component/ProcessRunner/ProcessRunner.php, src/Component/Ssh/Client.php, src/Deployer.php, src/Executor/Server.php, src/functions.php
- Upgrade phpstan version
- Fix issues reported by phpstan
https://github.com/deployphp/deployer/issues/2996
=> Phpstan issues

docs/recipe/provision/website.md, recipe/provision.php, recipe/provision/website.php
- [ x] Bug fix #2876, #2948 
Added side-enabled folder for collecting all site's configs in one place. The purpose is to fix bugs and add the ability to run several sites.
=> Site-enabled folder for Caddy configs

docs/installation.md
Fix Missing double quote in installation.md
=> Missing " in installation.md

docs/KNOWN_BUGS.md
=> deployphp/action#35 Add information about known `rsync` bug

docs/UPGRADE.md
=> Add upgrade docs about default_stage

docs/recipe/pimcore.md, recipe/pimcore.php
Pimcore database configuration is located in database.yaml file.
=> Pimcore recipe fixes

docs/api.md, src/functions.php
=> fix closing backtick for inline Markdown code

docs/installation.md
- Fix typo on "you", change to "your"
=> Fix typo on "you"

recipe/provision.php
fixed the issue by changing "python" to "python-is-python3" in packages list
=> changed python to python-is-python3 in package list

docs/recipe/laravel.md, recipe/laravel.php
=> Add octane tasks in laravel recipe

docs/tasks.md
Replace non-existing method "write" with "writeln".
=> docs: fix non-existing method "write"

recipe/provision/databases.php
=> Fix: #3319 - Receiving variables db_user and db_name

src/functions.php
Fixes #3349 (original bugreport #3347 moved to discussion #3348)
=> Add some notes on rsync --exclude option

docs/recipe/laravel.md, recipe/laravel.php
=> Added the laravel default folder storage/framework/cache to writable folders array

docs/hosts.md
=> Added more details for ssh forwarding and multiplexing

recipe/craftcms.php
Hello, 
I wanted to share my CraftCMS config file that I keep coping between projects. I am not sure what's the procedure to add a new recipe here, but I thought that opening a PR could be a good start.  
Thanks!
=> Add CraftCMS recipe

docs/getting-started.md
Only file edited was `getting-started.md` so no change via docgen
=> Documentation edits

src/Importer/Importer.php
=> Use include path when importing YAML files (resolves #3376)

src/Executor/Master.php, src/Executor/Messenger.php
=> Show failed tasks for CI-environments

recipe/deploy/release.php
* Avoid calling count() in loop
* Remove extra variable for release name
* Reverse the array before for clarity
=> Simplify loop in releases_list

src/Utility/Httpie.php
=> Fixes #3472

recipe/magento2.php
=> fix typo in magento recipe

docs/UPGRADE.md
=> Doc update about new default value of writable_recursive

recipe/shopware.php
=> Shopware recipe: Do not warm up cache when clearing the cache

docs/recipe/shopware.md, recipe/shopware.php
Resolves https://github.com/deployphp/deployer/issues/3529
=> Shopware: Add new task for refreshing themes

docs/UPGRADE.md
https://github.com/deployphp/deployer/issues/3541
=> Add missing information to UPGRADE.md

src/schema.json
=> fix: upload in yaml, allow array or string (#3551)

docs/recipe/laravel.md, recipe/laravel.php
See https://nova.laravel.com/docs/4.0/installation.html#keeping-nova-s-assets-updated
=> Add Laravel Nova task to recipe/laravel

recipe/symfony.php
=> add log_files to Symfony recipe

docs/recipe/yii.md, recipe/yii.php
=> Added migrate task to Yii recipe

src/Command/MainCommand.php
=> Add an option to don't show banner after a task

docs/KNOWN_BUGS.md, docs/basics.md, docs/ci-cd.md, docs/cli.md, docs/getting-started.md, docs/hosts.md, docs/selector.md, docs/tasks.md, docs/yaml.md
=> Update documentation, improve language, fix grammar and typos

docs/ci-cd.md
=> ci-cd docs: update link to gitlab doc section

docs/contrib/cachetool.md, docs/recipe/magento2.md, recipe/magento2.php
I have added a new feature to handle cron stop/start before/after deployment.
=> Add feature to stop cron before deployment and start cron after

docs/recipe/laravel.md, recipe/laravel.php
=> Update Laravel recipe add pulse tasks

recipe/shopware.php
Added an exemplary `deploy:update_code` task.
@Schrank is in progress of updating the recipe according to #3799 . I don't know the status of that.
Meanwhile, since the recipe is just not working at the moment, I propose to add the missing puzzle piece to make the current recipe working at all.
=> Shopware: Added `deploy:update_code`

src/Executor/Messenger.php
=> use md5 of task name for section id in gitlab ci

docs/recipe/provision.md, recipe/provision.php
> Hope its not an overkill. Looks nice in my console.
=> Improve the configuration options console output in provision:configure

recipe/laravel.php
=> Add tasks to start/restart Laravel Reverb

contrib/sentry.php
=> Raise Httpie timeout for Sentry

recipe/pimcore.php
Remove pimcore:custom-layouts-rebuild
=> Update Pimcore Recipe for version 11

src/Importer/Importer.php
=> Fix wording 'downlaod' -> 'download'

docs/recipe/cakephp.md, docs/recipe/codeigniter.md, docs/recipe/codeigniter4.md, docs/recipe/contao.md, docs/recipe/craftcms.md, docs/recipe/drupal7.md, docs/recipe/drupal8.md, docs/recipe/flow_framework.md, docs/recipe/fuelphp.md, docs/recipe/joomla.md, docs/recipe/laravel.md, docs/recipe/magento.md, docs/recipe/magento2.md, docs/recipe/pimcore.md, docs/recipe/prestashop.md, docs/recipe/silverstripe.md, docs/recipe/spiral.md, docs/recipe/statamic.md, docs/recipe/sulu.md, docs/recipe/symfony.md, docs/recipe/typo3.md, docs/recipe/wordpress.md, docs/recipe/yii.md, docs/recipe/zend_framework.md, src/Configuration/Configuration.php, src/Exception/Exception.php, src/Task/Task.php
=> Add nullable types to nullable function arguments

docs/ci-cd.md
Just added some docs for bitbucket. The example is a stripped-down version of what I'm using for a Laravel deployment, so it should be verbose enough for most starting points.
=> Added: bitbucket pipelines example

recipe/deploy/update_code.php
pick https://github.com/deployphp/deployer/pull/3996 into master branch
=> Report missing repository config in update-code task (#3996)

.php-cs-fixer.dist.php
=> Fix php7.4 after 7.5.6

src/Command/SelectCommand.php
Fixes failed test from previous change (https://github.com/deployphp/deployer/actions/runs/13051852957/job/36413743111?pr=4010).
=> Set default for default_selector

.github/workflows/lint.yml
similar to https://github.com/deployphp/deployer/pull/4016 but with a different min-php version
=> Lint sources on PHP 8.2 via Github Action

recipe/laravel.php
=> Fix tasks to start/restart Laravel Reverb in 7.x branch (#3959)

docs/recipe/shopware.md, recipe/shopware.php
Reverts deployphp/deployer#4059
@M-arcus Thanks for telling me, looked good from my point of view :-)
=> Revert "Shopware recipe: Share theme folder for atomic themes"

recipe/provision/nodejs.php
=> fix(provision): correct typo in node_version variable in notice

src/Utility/Rsync.php
https://github.com/deployphp/deployer/discussions/4073
=> Rsync does not check emptyness of "became" option
