composer.json

The phpseclib php5 branch autoloads according to PSR-4 namespacing so the client encryptionalgorithms array isn't empty.

Changed phpseclib dependency to php5 branch

---

src/Server/Local.php

Tasks like `composer install` can take really long. However in `Symfony\Component\Process` the method `run()` uses a default timeout of 60 seconds. Sometimes this value is too low. 
In #146 we discussed just to set a higher timeout value.

Set local process timeout to a higher value

---

recipe/common.php

Changed output when cloning repository, because of initialization of submodule. Git always output some text, and this is actually considered as error. Update provide possibility to deploy repository with submodules.

Change output for cloning repository

---

src/Console/TaskCommand.php

The symfony console has a `configure`-method which should be used to configure the command.

Fixed command configuration

---

src/Server/Builder.php
src/Server/Configuration.php
src/Server/Remote/PhpSecLib.php
src/Server/Remote/SshExtension.php
test/src/Server/BuilderTest.php

This pull request includes:
- Implement [SSH Agent Forwarding Feature #134 ](https://github.com/deployphp/deployer/issues/134)
- Unit test for `Builder::forwardAgent()` method   
How to use?
```php
<?php 
// file: deployer.php
server('deployer', 'domain.com', 22)
->forwardAgent();
```

Implement SSH Agent Forwarding Feature

---

src/Server/Builder.php
src/functions.php
test/src/Server/BuilderTest.php

This is just a proposal because i prefer more fluent like that:
```php
server('name')
->host('ec2-52-171-208-37.my-server.com')
->port('9876')
->path('/home/dir/dir')
->user('user')
->pubKey('~/.ssh/name.pub', '~/.ssh/name');
```
instead of:
```php
server('name', 'ec2-52-171-208-37.my-server.com', '9876')
->path('/home/dir/dir')
->user('user')
->pubKey('~/.ssh/name.pub', '~/.ssh/name');
```

Added host() and port() to Builder

---

src/functions.php

Here's my take on the `cd` function. I've also added a `within` function which allows the user to provide a callback:
```php
<?php
task('test', function() {
cd('my_dir');
within('{some_dir}', function() {
run('some command');
});
// back in my_dir
});
```
After the `within` function is called, the environment is reverted to the previous working path.
This current implementation only support going to an absolute path. We may consider changing the implementation to support relative navigation if that is something people would want (I don't think that is the case though).
Reference: #177.

Add cd (change directory) and within (run commands within a directory and revert to the previous workingPath)

---

src/functions.php

Regarding issue with timeout running local tasks that requires long execution.
This is a fix that allows the command to be attached with a timeout parameter optionally.

Possible override of runLocally task with timeout parameter optional.

---

recipe/common.php

If the shared paths do not exist in the release_path directory and those shared directories have a depth > 1, the directory structure must be created before symlinking can be done.

Create path to shared dir in release dir if it does not exist.

---

recipe/common.php
src/functions.php

If cd was given {release_path} as target path, it would attempt to run a command to figure out what the value of {release_path} is, which, in the process, would also want to know the value of {release_path} and so on.
The fix simply parses the value as it is given, thus making the result static instead of a closure.

Parse the target path given to cd to prevent recursive loop.

---

src/Server/PhpSecLib.php

Composer now outputs non-error messages to stderr. The `run` function should be check the exit status of the command, not the error output.

Check the exit status of the command instead of stderr

---

recipe/common.php
recipe/symfony.php
src/Server/Environment.php
src/functions.php
test/src/Server/EnvironmentTest.php

In this Pull request, I will implement feature of issue #211 
Change syntax for env vars to {{ ... }} and support allow whitespaces ( {{deploy_path}} and {{ deploy_path }} return same value).
Sorry by create other pull request.
This pull request is rebase of PR #218

Change syntax for env vars

---

src/Server/Remote/PhpSecLib.php

This is done to support applications which return a non-zero exit status but do not output error messages to stderr.

Return $result if getStdError() returns an empty string.

---

recipe/common.php

As described in issue #248 - the commands for deployment can fail with mysterious errors when remote server is running a non-POSIX shell (like tcsh, common on BSD systems). 
Added a simple check with expression - if it fails, user will see more friendly message explaining to switch to sh/bash/similar.

Added simple check if the shell on remote server is POSIX-compliant.

---

recipe/common.php

After task `deploy:writable`, we should restore working path.

Fix restore working path after task deploy:writable

---

src/Server/Environment.php
src/Type/DotArray.php
test/src/Type/DotArrayTest.php

In this PR: Change specific requirement for environment variables follow the discussion in #218 
1. Environment variable name will be checked and only allow a-z, A-Z, 0-9, underscore character ( `_` ) and dot character ( `.` ) .
2. If variable name having a dot character, variables could be used in the future to be a property of an array (`env()->set()`, `env()->get()`, `Environment::setDefault()`, `Environment::getDefault()` are implemented).
```php
env('abc.xyz', [1, 2, 3]);
var_export(env('abc'));
// output:
// array(
//     'xyz' => array(1, 2, 3)
// )
```
3. Environment variable parser for run command support below case:
```
{{ abcxyz }}  --> $env['abcxyz']
{{ abc_xyz }} --> $env['abc_xyz']
{{ abc.xyz }} --> $env['abc']['xyz']
```

Change specific requirement for env vars

---

recipe/symfony.php

In deployer v2 I had to copy the whole recipe to support the new symfony dir structure.
Migrating to v3, it feels very unprofessional, so I made some changes in it,
which makes it very easy to support projects adopting the new dir structure early on.
Usage example from my `deployer.php` file:
```php
require 'recipe/symfony.php';
// Switching to the sf3 dir structure
set('shared_dirs', ['var/logs']);
set('writable_dirs', ['var/cache', 'var/logs']);
set('bin_dir', 'bin');
set('var_dir', 'var');
```
Awaiting you opinions. :)

Changed the symfony recipe to support the v3 dir structure

---

build
src/functions.php

- Fixed the success sentence, which was outputted when a new phar build was finished,
- Added automatic environment variable registration to the `server` function ("host" and "name" variables),
- Added a `has` function, so that the existence of a parameter can be checked.
I'm awaiting your opinions.

Added some modifications into the global functions, and fixed a spelling mistake

---

recipe/laravel.php

Seems like the deploy:shared was forgotten from the Laravel recipe.

Shared directories and files is not getting called in Laravel recipe

---

src/Server/Environment.php
test/src/Server/EnvironmentTest.php

We didn't talk about this, but I think this feature is a natural addition.
Basic env parameters - especially ones that could be mentioned in the docs - should be protected from future changes, since many 3rd party and custom tasks can rely on these values.
Consider the env parameters set by the Builder (#272).
If a 3rd party task later desides to set the "server" env var, there's nothing to stop him in doing so.
Now if a developer just include that task in his deployment process without digging in the code and checking every detail, it can cause side-effects, since after that task runs, any following task that relies on the "server" env var will fail in some way.
At this point, the developer can easily misjudge the situation and believe that the depoyer code itself is buggy, while in …

Added the possibility of 'protected' env parameters. (+test).

---

src/Server/Environment.php
src/Type/DotArray.php
test/src/Server/EnvironmentTest.php

This pull request is fixing bug of pull request #276 .
> Note: This code using 
```php
if($len < $length && '.' === $name[$len] && 0 === strpos($name, $protectedName)) {
```
> it's performance better than 
```php
if(0 === strpos($name, $protectedName . '.')) {
```

Fix bug of pull request #276: add feature protected env params

---

src/Server/Builder.php
src/Server/Configuration.php
src/Server/Password/AskPasswordGetter.php
src/Server/Password/CallablePasswordGetter.php
src/Server/Password/PasswordGetterInterface.php
src/Server/Password/SimplePasswordGetter.php
test/bootstrap.php
test/src/Server/BuilderTest.php
test/src/Server/ConfigurationTest.php
test/src/Server/Password/AskPasswordGetterTest.php
test/src/Server/Password/CallablePasswordGetterTest.php
test/src/Server/Password/SimplePasswordGetterTest.php

1. Add AskPasswordGetter (ask password before connecting)
2. Add CallabackPasswordGetter (gets password with call callbacks, Closures)
For more information, please see #298

Add password getter system for customize getting password. (#298)

---

recipe/common.php
recipe/symfony.php

There is an issue with the release date : it's based on the client date.
It should be based on the server date.
How to reproduce:
- set your script to keep 2 releases
- set your server on UTC
- deploy twice from CircleCI (UTC)
- deploy once from a Europe/Berlin machine (or any other timezone as long as you more than 1 hour offset with UTC)
Releases:
- 20150612111941 : CircleCI (1st deployment) at 11:19:41
- 20150612113811 : CircleCI (2nd deployment) at 11:38:11
- 20150612093922 : Deployment from my machine at 11:39:22
The symlink task will symlink the latest release (20150612093922).
The cleanup will then remove the oldest release (20150612093922 too).
Only outdated releases will remain on the server : 20150612111941 and 20150612113811.
Using the server date ensures this situation does …

[BUGFIX] : Use server date

---

recipe/common.php

This enables faster git cloning by using options `--reference` and `--dissociate`.
By default if git on server is newer or equal to 2.3, git cache is enabled. However if user sees any drawbacks to using git cache and would rather use shallow clones, he is allowed to do so by simply setting env variable `git_cache` to `false`.
This work is based on deployphp/recipes#12 for same behaviour on local machine.

Ref #346 - faster git cloning

---

recipe/common.php

Will now create the deployment path during prepare if it doesn't exist.
See #402

Create the deployment path if it doesn't exist

---

src/Deployer.php
src/Stage/StageStrategy.php
test/src/Stage/StageStrategyTest.php

Added ability to set a default stage in parameters (see #345).
Enable it using:
```
set('default_stage', 'staging');
```
If it's not set then original behaviour is observed.

Add default stage support.

---

src/functions.php

I think it is a good thing to get the local / remote to be parsed through the env parser, so its possible to do things like
````php
task('copy:param:file', function() {
upload('.deploy/parameters.{{env}}.yml', '{{release_path}}/app/config/parameters.yml');
});
````
Right now I have created my own upload function, which "extends" the upload function
````php
function MyUpload($local, $remote)
{
$local = env()->parse($local);
$remote = env()->parse($remote);
upload($local, $remote);
}
````

Add env parsing to upload

---

src/Server/Remote/PhpSecLib.php

It temporary fixes problem that described in phpseclib/phpseclib#775.
For example `composer install` may be stoped on the middle of progress if it takes more than 10 sec.

Temporary fixes problem with command execution timeout

---

.gitignore
.travis.yml
src/Server/Remote/PhpSecLib.php
test/recipe/Helper/RecipeTester.php
test/recipe/RemoteServerTest.php
test/travis/setup-secure-shell.sh

It fixes wrong huge default value for timeout that was introduced in #429
IMPORTANT! To prepare ssh tests, I have to use `sudo: required` that means that all tests will run on old Travis infrastructure not [container-base](http://docs.travis-ci.com/user/workers/container-based-infrastructure/)

Implemented tests and fixed default timeout value to not soo huge

---

src/Task/Task.php
test/src/Task/TaskTest.php

Just little bit of syntactic sugar. What do you think?
**String at onlyOn method**
[That](https://github.com/deployphp/deployer/issues/408#issuecomment-125478786) example from #408 didn't work and [here](https://github.com/deployphp/deployer/issues/355#issuecomment-112614911) it was suggested to use strings too. But the method internally works with arrays, so it should either accept both arrays and strings or I think that there should be an `array` type hint.

Task: syntactic suger for onlyOn method

---

recipe/common.php

When run deploy:writable_dirs WITHOUT sudo, exception maybe thrown if setfacl run on files created by http user (in directory that has been setfacl before). These directories/files should be skipped.
Ref: https://github.com/deployphp/deployer/issues/433#issuecomment-133388894

Update deploy:writable_dirs: When running WITHOUT sudo, exec setfacl once only

---

recipe/common.php

This feature makes it possible to specify the user for `chmod` & `setfacl`. In my use case the PHP-FPM pool is using an dedicated user but Apache is served by www-data. Using `deploy:writable` all writable dirs would use the Apache user rather the pool user which causes permission issues when trying to set the file mode and owner.
You can now use the directive `set('http_user', 'username')` to set the user owning this files & directories.

Added support for setting http user for chmod

---

recipe/common.php

In a custom deploy strategy I want to be able to re-use the release timestamp, so it's the same on all places.

Make the current release timestamp available as environment variable

---

recipe/laravel.php

This fixes a bug when laravel tries to get the full path of these directories but returns false because they don't exist.
This is caused in some cases like the [view config](https://github.com/laravel/laravel/blob/master/config/view.php#L31),  because `realpath()` is used.
If we don't create each shared folder during the deployment, realpath returns false because the dir doesn't exist and thus laravel tries to write to the root `/` directory.
- **Deployer version:** master branch
- **PHP version:** all php versions
- **Deployment target(s) OS:** hmm, all

Updated shared dirs in laravel 5 recipe

---

.travis.yml

Php 7 is stable so it should be removed from failures

Remove php 7 from failures

---

recipe/symfony.php

| Fixed tickets | #419
Default is set to true - current configuration does not need to be changed.
If you do not use AsseticBundle just switch flag to false:
```php
set('dump_assets', true);
```

Flag for assetic:dump task #419

---

test/recipe/RemoteServerTest.php

Problem with tests has been appeared because Travis has changed IPv6 to IPv4 (see
"IPv6 no longer present" section in https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future)

Make more correct RegExp in RemoteServerTest

---

src/functions.php
test/src/FunctionsTest.php

| Fixed tickets | none, afaik
I've also modified the test for `upload` so that it verifies environment variable replacement.

Fix environment variable replacement in "download" function

---

src/Executor/ParallelExecutor.php
src/Executor/SeriesExecutor.php
src/Task/Task.php
test/fixture/recipe.php
test/src/Executor/ParallelExecutorTest.php
test/src/Executor/SeriesExecutorTest.php
test/src/Task/TaskTest.php

I have a use case where my `servers.yml` file is not a static list of servers. I have more than one production webserver, and the server information is pulled down from AWS and written to `servers.yml` each time I do a deployment. The number of production servers could increase or decrease based on needs, so I don't want to have to update the deployment script every time that happens.
This means I can't just do:
```php
task('task_name', function () {
})
->onlyOn('production1', 'production2', 'etc...');
```
However, I know that I always want to run that task on Production, regardless of how many Production servers I have. That is the purpose …

Added way to execute tasks only for certain stages

---

recipe/cakephp.php
recipe/codeigniter.php
recipe/composer.php
recipe/drupal7.php
recipe/drupal8.php
recipe/fuelphp.php
recipe/laravel.php
recipe/magento.php
recipe/symfony.php
recipe/wordpress.php
recipe/yii.php
recipe/yii2-app-advanced.php
recipe/yii2-app-basic.php
recipe/zend_framework.php
src/Task/Task.php
src/functions.php
test/src/FunctionsTest.php
test/src/Task/TaskTest.php

Changed:
- Allowed define task by a callable
- Migrated using `taskGroup()` function to define a task group
```php
taskGroup('deploy', [
'deploy:start',
'deploy:end',
]);
```

Feature task may be callable

---

src/Console/Output/OutputWatcher.php
src/Executor/Informer.php

| Fixed tickets | #555
The bug #555 was caused by using a wrong escape-sequence for the
terminal.  Instead of using \e[K it has used \e[k which actually has no
meaning and only bloats some noise on the terminal (except on OSX where
the noise is catched and hidden from the user). To see this behaviour
you need a real linux client for example a VM and you have to use it's
own terminal – not the OSX-terminal via ssh or something like that. Than
type the following example to see the behavior:
echo -e "aaaaaaaaa\r\033[k"
echo -e "bbbbbbbbb\r\033[K"
Furthermore the cursor is now set to the beginning of the line first to
really clean the line and not just something …

Fix bug #555 and clean output

---

bin/dep

Using this to deploy Joomla. Have a few autoloading scripts for Joomla only checking if JEXEC is defined. This allows my autoloads to return if DEPLOYER is defined.

Added constant DEPLOYER for other autoload scripts to check

---

.scrutinizer.yml
.travis.yml
composer.json
composer.lock

This introduces a change to the travis build that instructs builds with PHP 5.4 to use the lower bound dependencies.
| Fixed tickets | #495 
Fixes: #495 
Replaces: #556

Symfony 3 compatibility

---

src/Server/Remote/SshExtension.php

| Deprecations? |No
The `Ssh\Sftp\send` method return `false` on failure. The `!$this->session->getSftp()->send($local, $remote)` check will throw and exception if the file is empty (0 bytes sent).

Fixed SSH upload method bug

---

recipe/symfony.php

| Fixed tickets | #575 
As described in ticket #575 the cache is not writable after the deployment of symfony if the deployment-user is not the httpd-user. Therefore we would make the cache-directory writable again after the
cache-warmup.  This is necessary because symfony may not do that and the deploy user should know who is able to write into the cache.  You can finally define this by using `set('writable_dirs', […])` and
`set('http_user', '…')`.

Run deploy:writable again after cache warmup

---

bin/dep
recipe/common.php
src/Server/Environment.php
src/Type/DotArray.php
src/functions.php

| Deprecations? | Yes `composer_command`
| Fixed tickets | #548 #607 #586 #606
This is my version of custom bins. Here an example:
```php
task('default', function () {
run('{{bin/php}} -v');
run('{{bin/git}} --version');
run('{{bin/composer}} --version');
});
```
What do you think, guys?

Custom bin

---

recipe/common.php

Fix http user detection

---

recipe/common.php

| Fixed tickets | https://github.com/deployphp/deployer/issues/615

Fixed usage of composer.phar, when used as env/composer

---

recipe/common.php

This PR fix missing custom php binary for composer installer.

Fix custom php bin for composer install.

---

recipe/laravel.php

| Fixed tickets | #527 #572 
In this PR:
- Replace `php` by `{{bin/php}}`
- ~~Add helper tasks about migration and option `--force` can set by `env()`~~
- Resolved issues about shared directories and `.env` file
- Resolved issues about writable `storage` directory. Tested with `setfacl` on CentOS
- Changed order task deploy:shared and deploy:vendors in laravel recipe (See #619)

Bugfix laravel recipe

---

recipe/common.php

| Fixed tickets | #628 
In this PR:
- Using `trim` function to resolved issue #628 
- Change to using `{{bin/git}}` in checking git cache feature block

Fixed issue #628 and change using `bin/git` in check git cache feature

---

src/Server/Builder.php
src/Server/Configuration.php
src/Server/Remote/PhpSecLib.php

| Fixed tickets | 638
The underlying SFTP library allows for multiple authentication methods, so I've added a new setting AUTH_BY_IDENTITY_FILE_AND_PASSWORD.  I would imagine a better way to handle this would be to queue up each authentication method in an array and pass them as the arguments for the sftp->login() call, but I felt that I had too much potential to create breakage - so instead I created an additional method.
To use:
``` php
server('staging', 'example.com', 22)
->user('username')
->identityFileAndPassword() // Arguments are the 3 identityFile() arguments + the password() argument.  It will assume those defaults if nothing is passed. …
```

Enabling 2-factor with private key + password

---

recipe/typo3.php

[TASK] Add TYPO3 deployer recipe

---

recipe/symfony3.php

The `assetic:dump` command does not exist in Symfony 3. The `assetic` namespace has been replaced by `assets`. The new command to install assets is `assets:install`. 
This PR overrides the `deploy:assetic:dump` command so it works in Symfony 3. Ideally, the `deploy:assetic:dump` command would be renamed to something like `deploy:assets:install` in the main deploy task. However, this would mean overriding the entire list of tasks.

Fix assets installation in Symfony 3

---

src/Collection/Collection.php
src/Server/EnvironmentCollection.php
src/Server/ServerCollection.php
src/Task/Scenario/ScenarioCollection.php
src/Task/TaskCollection.php
test/recipe/CommonTest.php
test/src/Collection/CollectionTest.php

This PR only improves Collection classes by using `static::class` constant instead of `get_class()` function.

Improve Collection class by feature of PHP 5.5+

---

recipe/laravel.php

| Fixed tickets | #541 #619 
Added helper tasks:
- `artisan:migrate` => `artisan migrate --force`
- `artisan:migrate:rollback` => `artisan migrate:rollback --force`
- `artisan:migrate:status` => `artisan migrate:status`
- `artisan:db:seed` => `artisan db:seed --force`
- `artisan:cache:clear` => `artisan cache:clear`
- `artisan:config:cache` => `artisan config:cache`
- `deploy:public_disk` => Create symlink `public/storage` to `storage/app/public`

Add helper tasks for laravel recipe

---

recipe/common.php

| BC breaks?    | No (?)
| Fixed tickets | 
When the {{deploy_path}} is a symlink, find won't find any directories within it. To solve this, the trailing slash is required. This behaviour is explained here: https://chris-lamb.co.uk/posts/find-trailing-slashes-and-symbolic-links-directories

Fix deleting old releases, if deploy_path is a symlink

---

recipe/silverstripe.php

| Bug fix?      |  No
This pr adds a recipe to support the [Silverstripe CMS](http://www.silverstripe.org/software/cms/) 
- Follows the [composer recipe](https://github.com/deployphp/deployer/blob/master/recipe/composer.php)
- Adds `assets` to `shared_dirs` and `writable_dirs`
- Additional helper tasks for [generating the database schema](https://docs.silverstripe.org/en/3.3/developer_guides/model/data_model_and_orm/#generating-the-database-schema) and flushing the [cache/template/config manifests](https://docs.silverstripe.org/en/3.3/developer_guides/execution_pipeline/flushable/)

Add support for Silverstripe CMS

---

src/Executor/ParallelExecutor.php
src/Executor/SeriesExecutor.php
test/fixture/recipe.php
test/src/Executor/ParallelExecutorTest.php
test/src/Executor/SeriesExecutorTest.php

deploy.php
```php
task('deployer:start', function () {
if(runLocally('if [ -f start.txt ]; then echo "true"; fi')->toBool())
{
throw new \RuntimeException('deployer already started');
}
runLocally('touch start.txt');
})->desc('Deployer start')
->once()
->setPrivate();
task('deployer:end', function () {
runLocally('rm -rf start.txt');
})->desc('Deployer end')
->once()
->setPrivate();
```
result : 
PHP Fatal error:  Uncaught Error: Call to a member function parse() on null in /.../vendor/deployer/deployer/src/functions.php:316
functions.php
```php
function runLocally($command, $timeout = 60)
{
$command = env()->parse($command);
```
```php …
```

fix task once

---

src/functions.php

Currently, there's no way of actually seeing which files are being uploaded to the server. This PR adds the filename display of the file being uploaded when in debug mode (`-vvv`).

Show which file is being uploaded when in debug mode

---

.scrutinizer.yml
.travis.yml
composer.json
composer.lock

| BC breaks?    | Yes
| Fixed tickets | #745 
- Drop support PHP 5.5
- Add test on PHP 7.1 to TravisCI

Drop support PHP 5.5 and add test on PHP 7.1 to TravisCI

---

recipe/symfony.php

| BC breaks?    | ?
When i want to keep a "database:migrate" on my deploy file and when I have no migration in DoctrineMigrations Folder, cause break of the deploy.

Don't stop the deploy process when zero migrations

---

recipe/common.php

| Q | A |
| --- | --- |
| Bug fix? | Yes |
| New feature? | No |
| BC breaks? | No |
| Deprecations? | No |
| Fixed tickets | N/A |
When `--revision` option is setted, `update_code` does not take care of `git_cache`.
There is a comment "_To checkout specified revision we need to clone all tree_".
But if `git_cache` is used, all the tree is already cloned.
Else we just need to not shallow clone (setting `$depth=''`).

Use git_cache also when --revision is defined

---

recipe/flow_framework.php

With this recipe projects based on the Flow-Framework (https://flow.neos.io/) and Neos-CMS (https://www.neos.io) can be deployed.

FEATURE: Add Flow-Framework deployer recipe

---

src/Bootstrap/BootstrapByConfigFile.php

Array dot access doesn't work when importing servers from YAML, resulting in the error ```Object `identity_file.public_key` does not exist in Collection```.
This PR should fix this issue.

Fix array access

---

src/Server/Remote/NativeSsh.php

This tries to fix #889
`scp -r` does not work here, because `upload()` receives only files (not directories), so I've fixed it using `mkdir -p` before the `scp`. 
In order to improve performance, I've used a simple caching system with the private property `mkdirs`. Maybe it's not the ideal solution but I couldn't find anything better.

Make uploading recursive in ssh native

---

recipe/deploy/shared.php

Allow subfolders copy

---

src/functions.php

Replaced the `\RuntimeException` in `runLocally` with Symfony's `Symfony\Component\Process\Exception\ProcessFailedException` which has more information on the command that failed (including command line and error output).
The `ProcessFailedException` extends the `\RuntimeException` so there shouldn't be a BC problem.

Adjusted runLocally to throw ProcessFailedException in case of error

---

src/Server/Remote/NativeSsh.php

This bug meant that when deploying using a private key using ssh_type native would throw the following exception:
```
[Symfony\Component\Process\Exception\ProcessFailedException]
The command "scp -P '22' 'app-deploy.tar.gz' '[USER]@[IP]:[FOLDER]/releases/20161219151859/app-deploy.tar.gz'" failed.
Exit Code: 1(General error)
Working directory: /opt/atlassian/pipelines/agent/build
Output:
================
Error Output:
================
Write failed: Broken pipe
lost connection
```
It seems like this was just a simple copy-paste error.

Change variable which was (propably) copy-pasted wrong

---

recipe/deploy/writable.php

Just found this bug reading the source code. I think you meant to use `httpGroup` and not `httpUser` 😂

Fix bug with $httpGroup guard clause

---

src/Builder/BuilderInterface.php
src/Cluster/ClusterBuilder.php
src/Initializer/Template/FrameworkTemplate.php
src/Server/Builder.php
src/Server/Configuration.php
src/Server/Remote/NativeSsh.php
src/Server/Remote/SshExtension.php

Native ssh tty option feature

---

src/functions.php

Similar to other locations this is now also raised to 5 minutes.

Raise timeout for runLocally to 300 seconds

---

recipe/deploy/lock.php

always success when running unlock
Run `deploy:unlock` always return success instead of exception when `deploy.lock` not exist

always success

---

recipe/common.php

Try to remove deploy.lock when deploy is fail
Try to remove `deploy.lock` when deploy is fail to make it simpler

Try to remove deploy.lock when deploy is fail

---

CHANGELOG.md
src/functions.php

Similar to upload() a message should be shown for file downloads.
> Do not forget to add notes about your changes to [CHANGELOG.md](/CHANGELOG.md)

Show message on file download

---

src/Server/Remote/NativeSsh.php

Implementing ssh multiplexing speeds up NativeSsh extremely. Its faster than other methods.
https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
How to test? In your deploy.php file put:
```
set('ssh_type', 'native');
set('ssh_type_native_mux', true);
```
You should observe considerable increase of speed. When using mux the ssh authentication is done only once.

Add support for multiplexing for NativeSsh

---

recipe/magento2.php

add magento2 base recipe

---

CHANGELOG.md
src/Deployer.php
src/Server/Environment.php
test/src/DeployerTest.php
test/src/Server/EnvironmentTest.php

| BC breaks?    | Maybe
This ensures that something like the following works:
```php
set('top', [
'first' => [
'second' => [
'value1',
'value2',
],
],
]);
add('top', [
'first' => [
'second' => [
'value3',
],
],
]);
/*
The following should yield:
Array
(
[first] => Array
(
[second] => Array
(
[0] => value1
[1] => value2
[2] => value3
)
)
)
*/
print_r(get('top'));

Recursively add configuration options

---

CHANGELOG.md
recipe/common.php
recipe/deploy/writable.php

This commit enables the user to disable the recursive flag when setting writable dirs with `chmod`, by setting `writable_chmod_recursive` to `false`. It is per default set to `true`.
I have prefixed the setting with `writable_chmod_` to use the same naming convention as with `writable_chmod_mode`.
My personal scenario is that when I run the deployment, writable dirs are created by my own user and are then given 777 permission. The files within these writable dirs are then created by the web server user, and when I deploy the next time (without sudo), the deployment fails because the recursive flag makes the command trying to change …

Add non-recursive chmod flag to deploy:writable

---

CHANGELOG.md
src/functions.php

This PR enables the use of Symfony Console [autocomplete](http://symfony.com/blog/new-in-symfony-2-2-autocomplete-on-the-command-line) for `ask()` deployer function.
In my usecase, I use `ask()` to ask the user which branch he wishes to deploy, and since some branch names can be very long, autocomplete can be pretty handy.

Enable autocomplete for ask()

---

recipe/flow_framework.php

The deployer namespace was missing in the flow recipe and also the deprecated env methods were used.

TASK: Fix deployer namespace and remove deprecated method calls +

---

recipe/wordpress.php

* Configure files commonly shared across deploys (`wp-config.php` and the uploads folder)
* Run Composer (many WordPress sites use Composer with WPackagist)
* chown file to the web server owner. (Might be platform-dependent, but this is a good default)
| BC breaks?    | Yes (If someone  had include the old recipe)

Improve the WordPress recipe

---

CHANGELOG.md
src/Deployer.php
src/Server/Environment.php
src/Type/ArrayType.php
src/Type/Config.php
test/src/DeployerTest.php
test/src/Server/EnvironmentTest.php

| BC breaks?    | Maybe
| Fixed tickets | #962

Fix scalar options merge

---

CHANGELOG.md
src/functions.php
test/src/FunctionsTest.php

This is useful to reconfigure tasks defined in 3rd party recipes,
e.g. to limit execution to a few servers.
| Fixed tickets | #954

Add a way to retrieve a defined task

---

CHANGELOG.md
src/Console/CommandEvent.php

---
Ensure CommandEvent respects PHP syntax < 7.0.

Ensure CommandEvent respects PHP syntax < 7.0.

---

CHANGELOG.md
recipe/laravel.php

Laravel has an artisan command to send a restart signal to the queue workers. This is kind of a must during deployment. I noticed that the Laravel recipe does not have this artisan command, so here is a PR to add this command.
https://laravel.com/docs/5.4/queues#queue-workers-and-deployment

Add task queue:restart for Laravel recipe

---

CHANGELOG.md
src/Server/Remote/NativeSsh.php

| Fixed tickets | #979 
This PR adds support for specifying an SSH config file (e.g. `->configFile('~/.ssh/custom')`) and actually have it work in the NativeSsh implementation, using the `-F` option of the `ssh` program.

Support for SSH config file in NativeSsh implementation

---

CHANGELOG.md
recipe/deploy/release.php

Forces single column output and trims newlines from ls. On our servers, we have an alias for ls that improves the default output but was causing cleanup to not work.
| Fixed tickets | Unsure

Fixed an issue with the output of ls in releases_list that was breaking cleanup.

---

CHANGELOG.md
recipe/deploy/release.php

| Fixed tickets | Side effect noticed after fixing #1004 #1036
If as a user reduced their keep_releases by more than half of the number of releases they have on their server, the oldest would be ignored and not cleaned up. 
For example, if you have 100 releases on your server and reduce keep_releases to 20, only the most recent 45 releases would be read from the CSV. This would cause the oldest 55 releases to be ignored and not cleaned up.
The simple fix was to make sure it always reads as many lines from the CSV as there are release directories.

Fixed old releases not being cleaned up when keep_releases reduced by than half.

---

CHANGELOG.md
recipe/deploy/writable.php
test/recipe/CommonTest.php

| Fixed tickets | [PR#1000](https://github.com/deployphp/deployer/pull/1000)
I am not sure is it bug or not. Anton, it's up to you.

Create `writable_dirs` if they don’t exist

---

CHANGELOG.md
src/Server/Remote/NativeSsh.php

Change output of errors for native ssh (#1012)

---

CHANGELOG.md
recipe/common.php
src/Console/TaskCommand.php
src/Task/GroupTask.php
src/Task/ScriptManager.php
src/Task/Task.php
test/src/FunctionsTest.php

Updated version of https://github.com/deployphp/deployer/pull/934.

Add `--no-hooks` option for running commands without `before()` and `after()` (#934)

---

CHANGELOG.md
src/Type/Config.php
test/src/DeployerTest.php
test/src/Server/EnvironmentTest.php

This unbreaks e.g. the following:
```php
add('shared_files', ['foo']);
add('shared_files', ['bar']);
```
Without this fix, this would become `['bar']` instead of `['foo', 'bar']`.

Fix merge of string array config options

---

recipe/deploy/copy_dirs.php

Possibility to copy nested directories  ex:
set('copy_dirs', ['vendor', 'wp-content/plugins', 'wordpress']);
now it's not possible to copy for example: wp-content/plugins to the same location.

Copy nested directories

---

bin/dep

Pretty print uncaught exceptions using SymfonyStyle. Those exceptions occur e.g. when the enduser does not respect phpdocs and uses wrong argument types etc.
repro:
```
// inside your deploy.php
before('does_not_exist_task', 'do_something');
```
before
after

Pretty-print uncaught exceptions with SymfonyStyle

---

CHANGELOG.md
src/Server/Remote/NativeSsh.php

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | ubuntu16.04 lts
| Remote Machine OS | ubuntu16.04 lts
```
php -v
PHP 7.0.16-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:36:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.16-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
with blackfire v1.15.0~linux-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```
the copy using scp fails, as arguments are not properly escaped.
copy a directory which contains file, containing a space in the filename with the following task
```
task('deploy:update_code', function () {
download('.', '{{release_path}}'); …
```

fixed download of files when filename remote contains spaces

---

CHANGELOG.md
src/Server/Remote/NativeSsh.php

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | ubuntu16.04 lts
| Remote Machine OS | ubuntu16.04 lts
```
php -v
PHP 7.0.16-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:36:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.16-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
with blackfire v1.15.0~linux-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```
the copy using scp fails, as arguments are not properly escaped.
copy a directory which contains file, containing a space in the filename with the following task
```
task('deploy:update_code', function () {
upload('.', '{{release_path}}'); …
```

fixed uploading of files containing spaces

---

CHANGELOG.md
src/Task/Context.php
src/functions.php

before this change a newcomer to this project sees errors like 
```
PHP Fatal error:  Uncaught Error: Call to a member function getOutput() on boolean in /cluster/www/www/www/tools/deployer/src/functions.php:677
Stack trace:
#0 /cluster/www/www/www/tools/deployer/src/functions.php(685): Deployer\output()
#1 /cluster/www/www/www/tools/deployer/src/functions.php(567): Deployer\isQuiet()
#2 /deploy/kunzmann/stage/rocket/deploy.php(51): Deployer\ask('Zielstage (prod...')
#3 /cluster/www/www/www/tools/deployer/bin/dep(106): require('/deploy/kunzman...')
#4 /cluster/www/www/www/tools/deployer/bin/dep(107): {closure}()
#5 {main}
thrown in …
```

Provide a usefull error when ask*() is not used wihtin a task()

---

recipe/magento2.php

This fixes the first deployment for Magento2, where the `current` symlink does not yet exist.
Alternative approach would be to split the `deploy:magento`, en run the database upgrade *after* symlink changing, which would allow to enable/disable maintenance mode in the current directory; or share the maintenance flag between releases.
(Please double check, but I think the syntax is correct here)

Only enable/disable maintenance when current exists

---

CHANGELOG.md
recipe/laravel.php

| Fixed tickets | #1086
This add `artisan:storage:link`. We could add it by default, by adding it after `deploy:writable`. It only creates the link when no dir exists.

Add storage:link option

---

CHANGELOG.md
src/Ssh/Client.php

| Fixed tickets | #1192
Check the multiplex initialization, until it is working. Prevents async issues when prompting for a passphrase.

Check multiplexing until initialized

---

CHANGELOG.md
src/Exception/InitializationException.php
src/Ssh/Client.php

| Fixed tickets | #1220
This bumps the wait time for a passphrase to 30 secs. It also checks if the process is running, otherwise throw an immediate exception (for example, after entering the wrong passphrase)

Bump passphrase timeout to 30secs, check if process is running

---

CHANGELOG.md
recipe/laravel.php
recipe/magento2.php

Since Laravel 5.2 doesn't have `artisan storage:link` command, we can't call on versions below `5.3`.

Check laravel version before symlink storage

---

recipe/laravel.php

Fixed Laravel version parser
I have :
vagrant@homestead:~/sites/marso$ php artisan --version
Laravel Framework 5.4.14
You can see the differences:
```
<?php 
$result = 'Laravel Framework 5.4.14';
echo $result.PHP_EOL;
preg_match_all('/version\ (.+?)$/', $result, $matches);
echo 'Deployer Version 5.0.1 Result'.PHP_EOL;
var_dump($matches);
echo PHP_EOL;
preg_match_all('/([0-9\.])$/', $result, $matches);
echo 'Deployer Version 5.0.2 Result'.PHP_EOL;
var_dump($matches);
echo PHP_EOL;
preg_match_all('/([0-9]\.*[0-9]*)/', $result, $matches);
echo 'My Branch Result'.PHP_EOL;
var_dump($matches);
echo PHP_EOL;
```

Fix a parsing of laravel version in output "php artisan --version"

---

CHANGELOG.md
recipe/common.php
src/functions.php

Some systems, especially thin Docker images, do not have `which` command, used to locate path of `php`, `git`, `composer` etc.
This pull request adds method which should mitigate this on most systems, prioritizing `command` over `which` with fallback to `type`. This should cover most systems out there.
Related to #484, #607, #586
See [this SXC article](https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then) for more related info.

Mitigate missing `which` command on some systems

---

src/functions.php

Relates to issue #1254 
Fixes a PHP undefined index notice when no options are supplied in the $config variable.
| Fixed tickets | #1254

Upload and download undefined index notice

---

CHANGELOG.md
src/Executor/ParallelExecutor.php

When using the parallel execution mode deployer invokes the dep script directly.
Which is fine as long as you only have one php version in your environment (like Build-Servers).
To ensure the usage of the php version that is used to trigger deployer, this pull request adds the PHP_BINARY to the sub-command.

use php bin in parallel executer

---

CHANGELOG.md
src/Console/RunCommand.php
src/Deployer.php

This PR add `run` command:
```sh
dep run 'which php'
```
```sh
dep run 'which php' --hosts one,two,three
```

Add run command

---

CHANGELOG.md
src/Host/Host.php
test/src/Host/FileLoaderTest.php

Now it's possible to parallel deploy with this configuration:
```php
host('prod')
->hostname('45.32.112.252')
->set('deploy_path', '~/prod');
host('beta')
->hostname('45.32.112.252')
->set('deploy_path', '~/beta');
```

Fix bug with parallel deploy to same host

---

CHANGELOG.md
src/Executor/ParallelExecutor.php

option should be handled with an equal sign.
`ParallelExecutor` throws an error if you add user defined options.
```
[Symfony\Component\Console\Exception\RuntimeException]  
Too many arguments, expected arguments "command".       
Exception trace:
() at vendor/symfony/console/Input/ArgvInput.php:189
Symfony\Component\Console\Input\ArgvInput->parseArgument() at vendor/symfony/console/Input/ArgvInput.php:88
Symfony\Component\Console\Input\ArgvInput->parse() at vendor/symfony/console/Input/Input.php:63
Symfony\Component\Console\Input\Input->bind() at vendor/symfony/console/Command/Command.php:222
Symfony\Component\Console\Command\Command->run() …
```

Handle option value with equal sign

---

src/Host/Storage.php

In a multi user environment where multiple projects are located on the same instance(s)
if two or more users are deploying a project on the same environment, the generated hosts files
in the system tmp folder are overwritten or worse, the deploy will fail due to file permissions.
Make the persistent storage folder configurable or use the system tmp  as default if not possible.

Per user persistent storage

---

CHANGELOG.md
recipe/symfony.php

| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A
deploy:cache:clear task contains excess option "--no-debug". Because this option is already defined as **console_options** variable.

deploy:cache:clear task contains excess option "--no-debug"

---

CHANGELOG.md
recipe/deploy/update_code.php

This PR introduces an option to enable or disable the `--recursive` flag while cloning. The use case is that we only have submodules for development related stuff, so dropping the `--recursive` flag would be more performant and it would keep us from having to include deploy keys for those git repositories as well.
```php
set('git_recursive', true);
```
```bash
➤ Executing task deploy:update_code
...
[example.com] > /usr/bin/git clone  --depth 1 --recursive -q git@github.com:deployphp/deployer.git /srv/http/foobar/releases/9 2>&1
```
```php
set('git_recursive', false);
```
```bash
➤ Executing task deploy:update_code
...
[example.com] > …
```

Introduce git_recursive option

---

CHANGELOG.md
src/Task/Task.php
test/src/Task/TaskTest.php

Added once feature

---

CHANGELOG.md
recipe/laravel.php

- Updated Laravel recipe to not run 'artisan:optimize' on Laravel >= 5.5, as that command is now deprecated ([see upgrade notes](https://laravel.com/docs/5.5/upgrade)).
- Version check defaults to 5.5 if not found.

Laravel 5.5

---

CHANGELOG.md
recipe/magento2.php

| BC breaks?    | No?
According to the Magento opmization guide, the dump-autoload command should be called after the compiling of classes:
http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_perf-optimize.html
> After running setup:di:compile to generate classes, use composer to update the autoloader.

Run autoloader after compilation

---

src/functions.php
test/fixture/recipe/party.php
test/recipe/PartyTest.php

Calling invoke on a GroupTask throw a `Can't run group task.` exception.
Using `ScriptManager::getTasks` and a `SeriesExecutor` allows to use invoke on GroupTasks.

Adds support for GroupTask in invoke

---

CHANGELOG.md
src/functions.php

I fixed it because I can not do the operation written in the documentaion.
https://deployer.org/docs/hosts#multiple-hosts
```php
inventory('hosts.yml') // ← not Proxy return!
->roles('app')
...
```

Fix inventory method

---

CHANGELOG.md
composer.json

| Fixed tickets | xx
Added platform config to composer.json.
This ensures compatibility of composer.lock.
https://getcomposer.org/doc/06-config.md#platform

Added platform config to composer.json

---

CHANGELOG.md
src/Console/CommandEvent.php

should fix the typeerror:
```php
[ERROR] TypeError: Argument 4 passed to Deployer\Console\CommandEvent::__construct() must be an instance of Exception,
instance of Error given, called in phar:///usr/local/bin/dep/src/Console/Application.php on line 131 and
defined in phar:///usr/local/bin/dep/src/Console/CommandEvent.php:30
Stack trace:
#0 phar:///usr/local/bin/dep/src/Console/Application.php(131):
Deployer\Console\CommandEvent->__construct(Object(Deployer\Console\TaskCommand),
Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput),
Object(Error), 0)
#1 …
```

support php7 \Errors in CommandEvent

---

CHANGELOG.md
composer.json

seems like the finder is not required for deployer itself, just for the build and phpcs.
Moved it to be a dev dependency so hopefully it wont be bundled with the deployer phar

moved symfony finder to dev-dependency

---

recipe/magento2.php

http://devdocs.magento.com/guides/v2.2/config-guide/deployment/single-machine.html
Suggest to just update setup:upgrade. As noted [here](http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-uninstall.html#instgde-install-keep) you can keep generated code, which saves time for deploying. This is essentially the same but with one command.

Magento2: use setup:upgrade --keep-generated

---

CHANGELOG.md
recipe/deploy/release.php

| Fixed tickets | xx
Var `$releasesList` must be set before creating metainfo and folder for current release. Now current release name added in `$releasesList` twice.
```php
<?php
// Save metainfo about release
run("echo '$date,{{release_name}}' >> .dep/releases");
// Make new release
run("mkdir $releasePath");
run("{{bin/symlink}} $releasePath {{deploy_path}}/release");
$releasesList = get('releases_list'); // <-- Current release version already hear
// Add to releases list
array_unshift($releasesList, $releaseName);
set('releases_list', $releasesList); // <-- Release version add to array again
// Set previous_release
if (isset($releasesList[1])) { // <-- 0 and 1 …
```

Get releases list before create metadata for current release

---

CHANGELOG.md
src/functions.php

fix `within()` to also restore the working-path when the given callback throws a Exception

use try/finally to make sure working-path restore on Exceptions

---

src/Task/Task.php

just phpdocs. copy description to the shallow() method as this is what people see when working with IDEs.

phpdocs on shallow()

---

CHANGELOG.md
src/Console/AutocompleteCommand.php

Added a description to the autocomplete command.
while at it use the prefered "configure" method instead of overwriting __construct().

Add a description to the autocomplete command

---

CHANGELOG.md
src/Console/Application.php
src/Console/TaskCommand.php
src/Deployer.php

| New feature?  | Yes 
| Fixed tickets | #1481
Log unhandled Exceptions into logfile

Log unhandled Exceptions into logfile

---

composer.json
composer.lock
test/src/DeployerTest.php
test/src/Host/HostSelectorTest.php
test/src/Initiaizer/InitializerTest.php
test/src/Task/GroupTaskTest.php
test/src/Task/ScriptManagerTest.php

Brought to you by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

Upgrade PHPUnit

---

CHANGELOG.md
recipe/silverstripe.php

SIlverstripe 4 has moved their framework from the project root to the /vendor/ folder.
This pull requests fixes an issue where deployer attempts to call the SilverStripe 3 tasks on a Silverstripe 4 installation

Update silverstripe recipe to support silverstripe 4

---

CHANGELOG.md
src/functions.php

Make sure pop() is called when Callback errors in on(...) function

---

CHANGELOG.md
src/Exception/RuntimeException.php

| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A
Some applications throw errors without correctly logging the output to `stderr`. This is probably an error with the framework, but it makes it hard to debug errors. I've encountered this with both Magento2 and Laravel, the only solution is to re-run the deployment with -vvv to see the error.
Proposed solution:
Show the regular output in RuntimeException, when the error output is empty.

Show regular output when errorOutput is empty

---

CHANGELOG.md
src/Console/DebugCommand.php
src/Deployer.php

| Fixed tickets | #1488 
Not sure if this was the correct route, to create a command for it. I noticed (after creating the command) that some other utilities (like the `config/hosts.php`) were just written as tasks.
If I need to rewrite this - let me know.

Add DebugCommand to display task execution order

---

src/Host/FileLoader.php
src/Host/Host.php
src/Ssh/Client.php

| Fixed tickets | #1171
I added the property "shellCommand" to the Host-class to change the shell used for commands over SSH. This is handy if the remote server has a non-standard location of the bash-binary or if some additional arguments are required.
My server sets some important environment-variables in "/etc/profile", which is not loaded for non-login-shells. So I use this feature to add the flag "-l" to start an login-shell:
```php
host('example.com')
->shellCommand('bash -ls')
```

Make used shell configurable

---

CHANGELOG.md
src/Exception/RuntimeException.php
src/Host/Host.php
src/Ssh/Client.php

I have added the becomeSetHome method to add the -H flag when become is used. In this way is possible to use home directory of the current user.

added becomeSetHome method to add -H flag when using sudo

---

CHANGELOG.md
recipe/magento2.php

Magento's module states are stored in app/etc/config.php. This task ignored that and blindly enabled all installed modules.
| BC breaks?    | Yes? If anyone relied on that task. Don't know why they would have though.

Remove magento:enable from Magento 2 recipe

---

CHANGELOG.md
recipe/deploy/cleanup.php

| Bug fix?      |  No
I couldn't enter a password using the option _cleanup_use_sudo_. I added the function cleanup_tty similar to writable_tty.

Extend deploy:cleanup with tty allocation when using sudo.

---

CHANGELOG.md
src/Executor/ParallelExecutor.php

When running deployer in parallel, we noticed the server that manages the deployments is running with 100% CPU usage. Debugging this issue we noticed that the `OarallelExecutor` is checking the process status in a while loop until the task is finished. However, as this is executed that much with no sleep in between, the CPU usage goes to 100% as it's constantly checking the status.
This PR add's a small usleep between every run which is neglectable for task performance, as a task can only take 1000 microseconds longer. The same logic is used in the Symfony Process class for the `wait` function. CPU drops to +/- 10% on my local machine with …

Sleep between process status calls to prevent 100% CPU usage

---

CHANGELOG.md
src/functions.php

to optimize resource consumption.
before this change, the number of subprocesses required to locate a binary was 2 in the best case and 6 in the worst case.
after this change it always requires 1 process, no matter which command will be used at the end (whether `command -v`, `which` or `type -p`)

locate binary with less subprocesses

---

CHANGELOG.md
recipe/common.php

`CI` environment variable is set in all the major CI environments:
* https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
* https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables
* https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html
* https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
And in those CI envs git user is almost always not set.
This patch helps when using and auto-deploy strategy to identify the automated deploy.
For the records: :rocket: :champagne: Deployer :heart:

Set custom user for CI environments

---

CHANGELOG.md
recipe/laravel.php

`cache:clear` command will clear users' sessions if CACHE_DRIVER is the same as SESSION_DRIVER, I think users should call this task on demand instead of putting it in default deploy task.

Laravel deploy task should not call cache:clear

---

CHANGELOG.md
src/Console/SshCommand.php

Allow the remote shell path to be overridden by host config -> right now i have the case that $SHELL is incorrect on the remote but I can't fix it (shared hosting). Secondly with this implementation I can explicitly select the shell via Host Config
| Fixed tickets | #1709
>
>
>

Allow the remote shell path to be overridden by host config

---

CHANGELOG.md
src/Utility/Httpie.php

We should use array_merge to append and reindex header array, + or union causes an issue where if we add a header, like for example Authorization, then the first item in merged header array will be skipped (Content-Type) as there will already be an item at 0 index of array. + does not replace values which keys already exist in arrays and does not append them for numeric indexes. If we add two headers then none of the headers in this class will be present in the final header array.

fixed default header override caused by array union

---

CHANGELOG.md
recipe/laravel.php

Hi,
This pull request adds the `horizon:terminate` command to the Laravel recipe. This is typically used in deployments when using Laravel Horizon.

Added horizon:terminate to the Laravel recipe

---

.travis.yml

| Fixed tickets | #1731
I changed `.travis.yml`. Because `sudo: false` is deprecated.
I checked this article and doc.
- `sodo false` is deprecated. ( Travis CI moves from build by container to build by vm)
- https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
- installing apt-package and `apt update`
- https://docs.travis-ci.com/user/installing-dependencies/

Removed `sudo: false` from .travis.yml

---

CHANGELOG.md
recipe/symfony.php
recipe/symfony4.php

This PR add `migrations_config` option to the Symfony recipes to specify Doctrine migration configuration to use.

Added `migrations_config` option to the Symfony recipes

---

bin/dep

If an error occurs in `dep`, output a message to STDERR, set the error code to 1 . 
example : if user use php 5.x.
```console
$ ./bin/dep
Upgrade to php7
Deployer 5.x supports only php7 and above.
If you want to use older php version use Deployer 4.x
$ echo $?
1
```
I think this is good way to end script by error.

Output message to STDERR at dep command

---

CHANGELOG.md
src/Support/Changelog/Parser.php

Fixed parser errors by adding the trim function to the changelog parser tokens.
| Fixed tickets | #1755

Added trim function to the changelog parser tokens.

---

bin/changelog
src/Support/Changelog/Item.php
src/Support/Changelog/ParseException.php
src/Support/Changelog/Parser.php
src/Support/Changelog/Version.php
src/Support/helpers.php

Some small code styles fixes:
1. Update missing argument in PHPDoc.
1. Splits the IF-statement/workflow(s) for readability
1. Replace double quotes to single quotes.
1. Replaced alias functions by original functions.
1. Define return types.
1. Type casting can be used
1. Non-optimal regular expression, \d is a subset of \w.

Code style fixes

---

CHANGELOG.md
recipe/sulu.php
recipe/sulu2.php
recipe/symfony4.php

Added recipe for sulu 1.x and uses `add` function instead of duplicate the `writable_dirs` and `shared_dirs` from symfony in sulu 2.x recipe.
Related to #1758

Added recipe for sulu 1.x and improve sulu 2.x recipe

---

CHANGELOG.md
src/Utility/Rsync.php

This fixes errors when attempting to upload a path containing spaces.

Escape arguments passed to rsync shell command

---

CHANGELOG.md
src/functions.php

If a host has a 'become' option set, it seems sensible that rsync uploads
should also be performed as that same user, which is currently not the case.
This change makes rsync run as the 'become' user by running sudo on the
remote side, just like how 'become' is implemented for normal SSH commands.

Let rsync honor 'become' option for host

---

CHANGELOG.md
recipe/laravel.php

Laravel recipes failing while remote deploy being unable to complete `set('laravel_version'..)`.
Change directory before `{{bin/php}} artisan --version`.
```
[Deployer\Exception\RuntimeException (1)]                                                             
The command "/usr/local/bin/php /var/www/mir24-app/mir24.tv/releases/2/artisan storage:link" failed.  
Exit Code: 1 (General error)                                                                          
Host Name: example-host                                                                              
================ …
```

Fix laravel set version

---

CHANGELOG.md
recipe/deploy/writable.php

| BC breaks?    | Yes 
| Fixed tickets | #1778 
My Bash is really bad, so I would highlight the fact that this needs reviewing. I tried deploying on three servers (with 0/1/3 http_user candidates) and it worked as expected - only the server with a single unique candidate detected http_user. Of the three servers, two were ubuntu servers and one was my local machine which is macOS.
Another important note is that this will break BC for users who were lucky to have multiple http_user candidates, and the first one from the list was the correct one - so consider maybe delaying this for the next major release.
If there is anything else I can help please let me know :)

http_user detection command could return wrong user

---

CHANGELOG.md
src/Executor/ParallelExecutor.php
src/Task/Task.php
test/fixture/recipe/parallel.php
test/recipe/ParallelOnceTest.php

| Fixed tickets | #1419 
Prevent multiple execution of tasks marked as `once()` when the `--parallel` and `--limit` option are used

Fix task(...)->once() with --parallel and --limit

---

src/Console/Input/Argument.php
src/Console/Input/Option.php
src/Console/Output/VerbosityString.php
src/Executor/ParallelExecutor.php
test/src/Console/Input/ArgumentTest.php
test/src/Console/Input/OptionTest.php

| Fixed tickets | https://github.com/deployphp/deployer/pull/1721#issuecomment-453936737

improve ParallelExecutor::generateOptions to manage all types of InputOption

---

CHANGELOG.md
src/Console/Input/Option.php
src/Executor/ParallelExecutor.php
test/src/Console/Input/OptionTest.php

| Fixed tickets | #1792 comment

Properly handle input options

---

src/functions.php

v 6.4.0 introduced the option for rsync to honor the `become` option on a host, however that code was placed only on the `download` function and not the `upload` function. This fixes that and allows rsync upload to honor `become`
>
>
>

Fix rsync upload honor become option for host

---

composer.json

…upload() function
This reverts commit 30c7f43f
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 
https://www.patreon.com/deployer
#####################################################################
>
>
>

Revert "moved symfony finder to dev-dependency (#1702)" as it breaks upload() function

---

UPGRADE.md

This is just a suggested change to a readme, no code change.
---
In the "Upgrade from 4.x to 5.x," section,
previously, the suggested mapping for `server($name, $hostname)` to `host($hostname)` silently dropped the $name, which will not retain the same command line calling argument.
There's no need to drop the $name, moving from 4.x to 5.x just changes the way it's declared. So this PR adds more precise suggested mapping, so that users will have smoother transition when upgrading.

More accurate mapping from v4 server to v5 host

---

CHANGELOG.md
recipe/deploy/update_code.php

PR https://github.com/deployphp/deployer/pull/352 introduced `--reference` and `--dissociate` flags while cloning the repo.
But [git-lfs](https://github.com/git-lfs/git-lfs/) needs the reference after the clone in order to download the files from the reference, and so getting the benefits of the previous clone seen as a cache.
Disabling `--dissociate` accomplish the git-lfs download from previous release.
Ping @johnny-bit as original author

Git: add option to disable --dissociate flag on cloning

---

CHANGELOG.md
recipe/common.php
recipe/deploy/writable.php

| Fixed tickets | #1822
Added `writable_recursive` option (default: true) used in all writable modes (chmod, chown, chgrp, acl)

Added `writable_recursive` option (default: true) used in all writable modes (chmod, chown, chgrp, acl)

---

.travis.yml

Stated that the community seems to already trust the state of art of the PHP 7.4 branch (see e.g. [Ocramius/ProxyManager](https://github.com/Ocramius/ProxyManager/blob/2.3.1/composer.json#L22)), I suggest to start right now to test PHP 7.4 and require green builds (so no `allow_failures`)

[Travis] Test againt PHP 7.4

---

CHANGELOG.md
recipe/wordpress.php

| Fixed tickets | xx
A default wordpress project doesn't include an composer.json file, which causes it to crash.
There is however a community project, only isn't this officially supported from wordpress.
I think a package like php deployer should support the official implementation.

Support default wordpress implementation

---

CHANGELOG.md
recipe/laravel.php

| Q | A
| - | -
| Bug fix? | No
| New feature? | Yes
| BC breaks? | No
This PR adds `artisan:optimize:clear` task to the Laravel recipe. It's available for versions 5.7 and up. 
I did not add it to the deploy script. 
I've also readded support for `artisan:optimize` for versions 5.7 and up. This command was deprecated in 5.5, removed in 5.6 and readded in 5.7 with different functionality. 
The previous version (<5.5) optimized composers autoload files.
The new version (>5.7) caches the app config and routes. It's the same as running `config:cache` and `route:cache`.

Add artisan:optimize:clear to Laravel recipe

---

recipe/magento2.php

I improve the list of the files/folders shared and etc. These changes add the new folders extremely required in both version (e.g. `var/session`), also add new folders to be compatible with the Magento ^2.2 (e.g. `generation`), but keeping the old folders to keep the compatibility (e.g. `var/generation`).
If you have any question, please let me know!

Recipe Magento 2 > Change the shared folders

---

src/Support/Unix.php
test/src/Support/UnixTest.php

Fix home-directory tilde-expansion (~) for paths containing a tilde

---

recipe/deploy/shared.php

If "shared" directory is already existing just do not call mkdir, to prevent pointless update during processing of the "shared" files just like it's checked during "shared" directories processing.

Prevent dir creation when it is existing

---

CHANGELOG.md
recipe/laravel.php

Instead of only calling view:clear command, starting from 5.6 laravel version it is possible to cache views

Laravel view cache task

---

recipe/deploy/writable.php

See:
* https://github.com/deployphp/deployer/issues/1778#issuecomment-507228046
* #1805
| Fixed tickets | #1778, #1805
before:
```
[192.168.10.10] > ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww  
-data|[n]ginx' | grep -v root | sort | awk '{print }' | uniq                 
[185.22.232.51] < httpd           apache                                     
[185.22.232.51] < nginx           apache                                     
[185.22.232.51] < php-fpm         apache                                     
```

Fixed bug "Can't detect http user name."

---

recipe/magento2.php

[HOTFIX] - magento2 recipe - Properly handle 'generated' and not 'generation' directory for >= 2.2.x Magento versions

---

CHANGELOG.md
recipe/laravel.php

- Re-added the `artisan:view:clear` task 
- Change the `artisan:view:cache` task to only run the `view:cache` command, as `view:clear` is already executed in the `view:cache` command in the framework (https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Foundation/Console/ViewCacheCommand.php#L33)

Update Laravel View Cache commands

---

CHANGELOG.md
recipe/laravel.php

Laravel supports automatic discovery of events and listeners since
version 5.8.9. (https://laravel.com/docs/5.8/events#event-discovery)
As the documentation states, you want to cache the manifest of event
listeners in a production environment to prevent scanning the
directories on every request.
The new tasks are not added to the deploy task because automatic event
discovery is opt-in functionality in Laravel.

Add tasks to cache a manifest of event listeners

---

CHANGELOG.md
recipe/deploy/shared.php
test/fixture/recipe/deploy.php
test/fixture/repository/app/config/parameters_dev.yml
test/fixture/repository/app/config/parameters_prod.yml
test/recipe/DeployTest.php

| Fixed tickets | https://github.com/deployphp/deployer/issues/374
There are cases where sharing directory does not work and many dynamic files must be shared across releases. For example symfony configuration does not load properly from symlinked folders (here `config/dynamic` is a shared dir):
```
In FileLoader.php line 168:
The file "../config.yml" does not exist (in: /var/www/project/releases/10/src/../config/dynamic) in ../config.yml (which is being imported from "/var/www/project/releases/10/src/../config/dynamic/config_a6gr2.yml"). 
In FileLocator.php line 71:
The file "../config.yml" does not exist (in: /var/www/project/releases/10/src/../config/dynamic). …
```

Handle asterisk wildcard in shared files

---

CHANGELOG.md
src/Deployer.php
src/functions.php

fixed invalid phpdoc

---

CHANGELOG.md
recipe/config/current.php
recipe/config/hosts.php

Updated the `config:hosts` and `config:current` tasks so they only output content for the stage given in the command, just like `config:dump` does.
EDIT: I said yes to the bugfix question, but I guess I'm not sure it really qualifies as a bug. Sorry if that's not the case.

Update config:hosts and config:current task recipes

---

CHANGELOG.md
recipe/symfony4.php

Fix wrong change introduced in https://github.com/deployphp/deployer/commit/62db938884cb0cc43e85af67a300bcf9f58807dd
`.env` file should not be shared because it's release-specific. On the other hand, `.env.local` and `.env.local.php` files are specific to deployment environment and should be shared between releases.
See for details: https://github.com/deployphp/deployer/pull/1907#issuecomment-533779139
| BC breaks?    | Yes
>
>
>

Update symfony4 recipe

---

CHANGELOG.md
docs/configuration.md

Addresses issue #1866
Clarified that you need to set a `default_stage` in your Deployer script, and also changed the default in the example code to `staging` since I think that is a more likely real-world default setting than `production`.
| Bug fix?      |  No
| Fixed tickets | 1866

Minor tweak to docs to clarify deploy_stage variable

---

recipe/silverstripe.php

Updated for SS4. Checks to see if assets is in root or public/assets as per SS4 new directory structure

SS4 fix to new assets dir location change

---

CHANGELOG.md
src/Ssh/Client.php
src/Utility/Rsync.php

I hate to bring the bad news here after your previous efforts to support Symfony 5, but there are still incompatibilities with symfony/process` 5.x in the Rsync- and SSH-client. This PR should fix them.
>
>
>

More Symfony 5 compatibility fixes

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
docs/advanced/deploy-strategies.md
recipe/deploy/check_remote.php
recipe/silverstripe.php

I'd normally submit two separate PRs but noted the request to update the changelog so have bundled them together and pre-emptively added a 6.7.4 entry. Hope that's okay!
I documented `check_remote` task usage in deploy-strategies.md but wasn't sure if this was the right place. Let me know if you want that moved.
| BC breaks?    | No (as far as I can tell)
| Fixed tickets | #1989 & #1990

Fixes for check_remote task and SS recipe

---

CHANGELOG.md
recipe/deploy/clear_paths.php

One run much faster than several. 
For example, we have 13 items for delete and it took ✔ Ok [4s 374ms], with one run it takes ✔ Ok [307ms]

Speedup deploy:clear_paths

---

CHANGELOG.md
recipe/deploy/check_remote.php

I noticed some other issues with this task so have done my best to tidy it up. I'm not a git expert but I've tested my changes and think there are some solid improvements here.
* Support branch & tag if specified
* Support shortened commit hashes
* Skip on first deployment
* Get true current ref from git
| Fixed tickets | #1994

Fix check_remote task revision resolution

---

CHANGELOG.md
recipe/symfony4.php

| Fixed tickets | https://github.com/deployphp/deployer/issues/1944
Unfortunately, the symfony4 recipe is not compatible with tasks for symfony3 recipe, because the `bin/console` includes the `bin/php` and there are no `console_options` defined.
Therefore we changed the definition of `bin/console`!

fix backward compatibility of bin/console for symfony4 recipe

---

CHANGELOG.md
recipe/deploy/lock.php
src/Deployer.php

This minor change guesses the local name of the `deployed.phar` script (or `./vendor/bin/dep`) for using in console output.
Example with a locked deployment:
```bash
$ dep deploy 
Deploy locked.                                        
Execute "dep deploy:unlock dev" to unlock.
```
```bash
$ ./vendor/bin/dep deploy 
Deploy locked.                                        
Execute "./vendor/bin/dep deploy:unlock dev" to unlock.
```
```bash
$ php vendor/bin/dep deploy 
Deploy locked.                                        
Execute "php vendor/bin/dep deploy:unlock dev" to unlock.
```
```bash
$ php deployer.phar deploy 
Deploy locked. …
```

Keep consistency with deployer executable naming

---

recipe/common.php

As stated in https://github.com/deployphp/deployer/issues/869 the copy_dirs task works relative to release_path rather then deploy_path as indicated by the comment in recipe/common.php
| Fixed tickets | 869

Fix comment in common recipe

---

CHANGELOG.md
src/Executor/ParallelExecutor.php
src/Ssh/Client.php

| BC breaks?    | Not sure
| Client OS | macOS 10.15.3
| Host OS |  Ubuntu 16.04.6 LTS
Hi!
When i'm deploying to multiple servers i use the `-p`, but most of the time due to task output containing control characters causes the terminal output to be garbled.
When the symfony process is created with tty enabled it causes to use my local machines /dev/tty 
this renders all output handling useless (nofi).
The `$process->getOutput()` does not return anything because there is nothing to return.
So i disabled it tty and added a closure that outputs the process, i could imagine this is not ideal so added an config option where the old behaviour can be forced. 
I'm only …

Output with parallel task execution was garbled

---

recipe/deploy/update_code.php

If you are using a branch named with a single quote, you will get the next error `bash: line 1: unexpected EOF while looking for matching `''`
This pull request fixes it.

Fix the use of a branch or tag name containing a single quote

---

CHANGELOG.md
src/Executor/ParallelExecutor.php
src/Ssh/Client.php

Reverts deployphp/deployer#2016

Revert "Output with parallel task execution was garbled"

---

CHANGELOG.md
bin/dep
recipe/common.php

- Added support for composer v2 installed.json format 
- Only use bin/php on composer.phar

Added support for composer v2 installed.json format + composer.phar fix

---

recipe/deploy/shared.php

Right now `deployer shared` would install the shared directory
once; when the first deployment of e.g. a branch is running.
Adding items to a shared resource in git will not update the
deployments shared folder. This is often confusing for our devs
who are required to add some assets sometimes.
I'd suggest this simple "fix" to always update the shared folder
from the git repository.
Signed-off-by: Mark Kusch <mark.kusch@transfermarkt.de>
#####################################################################
I'm working on **first LTS release** of Deployer. 
Please, consider supporting Deployer development on Patreon page: 
https://www.patreon.com/deployer
##################################################################### …

Always update shared folder from git

---

CHANGELOG.md
recipe/magento2.php

you can now `set('static-content-locales', 'en_US de_DE');` in you deploy.php to deploy multiple locales instead of just en_US
| Fixed tickets | #2040
> Do not forget to add notes about your changes to CHANGELOG.md. A command line tool has been included to make this easy, see [CONTRIBUTING.md](CONTRIBUTING.md#update-the-changelog) for details.

support for locales in static-content deployment

---

.github/PULL_REQUEST_TEMPLATE.md

The relative path does not work in pull request itself.
| Bugfix?      | Yes
> Do not forget to add notes about your changes to CHANGELOG.md. A command-line tool has been included to make this easy, see [CONTRIBUTING.md](CONTRIBUTING.md#update-the-changelog) for details.
Bein on Pull Request view:
- https://github.com/deployphp/deployer/pull/2038
The relative link in PR view will point to:
- https://github.com/deployphp/deployer/pull/CONTRIBUTING.md#update-the-changelog
which will be redirected to:
- https://github.com/deployphp/deployer/compare/CONTRIBUTING.md?expand=1#update-the-changelog

Use absolute url for CONTRIBUTING

---

CHANGELOG.md
contrib/slack.php

This PR adds a new task on the Slack recipe, to send a notification in case of rollback.
Usage:
```php
after('rollback', 'slack:notify:rollback');
```
Thank you,
Ben

Add a rollback notification task on Slack

---

composer.lock

The symfony/process v5.0.8 release contains a fix for the annoying
input/output error messages on PHP 7.4.
Example:
fread(): read of 8192 bytes failed with errno=5 Input/output error
See: https://github.com/symfony/symfony/pull/36380
Package operations: 0 installs, 7 updates, 0 removals
- Updating symfony/polyfill-php73 (v1.15.0 => v1.16.0)
- Updating symfony/polyfill-mbstring (v1.15.0 => v1.16.0)
- Updating symfony/console (v5.0.7 => v5.0.8)
- Updating symfony/process (v5.0.7 => v5.0.8)
- Updating symfony/polyfill-ctype (v1.15.0 => v1.16.0)
- Updating symfony/yaml (v5.0.7 => v5.0.8)
- Updating phpdocumentor/reflection-common (2.0.0 => 2.1.0)
| Fixed tickets | …

Update composer dependencies to include symfony/process v5.0.8

---

CHANGELOG.md
recipe/deploy/rollback.php

Let `rollback` fail if there are no more releases to revert to

---

src/Task/Task.php
src/functions.php

I've started to create a POC for our deploying needs and noticed that the follow snippet threw an error in the master branch:
```php
task('build', function() {
run('echo "hello world" > build.txt');
})->local();
task('deploy', function() {
invoke('build');
});
```

Fix Property "seriesExecutor" does not exist.

---

CHANGELOG.md
contrib/crontab.php

Recipe for crontab.
Example:
```
set('crontab:jobs', [
'*/5 * * * * /usr/bin/php -f /home/www-data/public/index.php cron checkDomains > "/dev/null"',
'*/10 * * * * /usr/bin/php -f /home/www-data/public/index.php cron checkServers > "/dev/null"',
]);
```

Crontab recipe

---

src/functions.php

`OutputInterface` have next definition, and `$options` is the third parameter of `write`, not second:
```
/**
* Writes a message to the output.
*
* @param string|iterable $messages The message as an iterable of strings or a single string
* @param bool            $newline  Whether to add a newline
* @param int             $options  A bitmask of options (one of the OUTPUT or VERBOSITY constants), 0 is considered the same as self::OUTPUT_NORMAL | self::VERBOSITY_NORMAL
*/
public function write($messages, bool $newline = false, int $options = 0);
```
| Bug fix?      | Yes or No
| New feature?  | Yes or No
| BC breaks?    | Yes or No
| Deprecations? | Yes or No
> Do not forget to add notes about your changes to CHANGELOG.md. …

Fixed: Bug

---

recipe/shopware6.php

| BC breaks?    | Yes
There were a bunch of things missing in the Shopware 6 recipe. These were probably hidden in the previously referenced `build.sh`, which doesn't exist in a normal Shopware 6 installation (or Deployer itself).
I've also added `.psh.yaml.override` in the shared_files so database credentials don't have to be committed to the Git repo. I also added missing `composer install` and database migration task.

Updated Shopware 6 recipe

---

docs/flow.md

Required git version is in fact 2.3 and git_cache is enabled by default then. Also clarified a bit what caching means.

Update regarding deploy:update_code

---

CHANGELOG.md
recipe/deploy/lock.php
test/recipe/DeployTest.php

| Fixed tickets | #2150 
This PR

Enhancement: Add deploy:is-unlocked

---

.travis.yml

This PR
💁‍♂️ It's already updated on Travis. For reference, see
- https://travis-ci.org/github/deployphp/deployer/jobs/722653436#L192
- https://travis-ci.org/github/deployphp/deployer/jobs/722653436#L215

Fix: Do not bother updating composer

---

recipe/shopware6.php

Do not update upgradeable plugins, it updates code too. What we actually want is to run the migration. But the database:migrate --all command only runs the migrations for the core. Added a task that runs migrations for all plugins too.
| Bug fix?      | Yes or No
| New feature?  | Yes or No
| BC breaks?    | Yes or No
| Deprecations? | Yes or No

Add sw:plugin:activate:all and sw:plugin:migrate:all to Shopware 6 recipe

---

CHANGELOG.md
src/functions.php
test/src/FunctionsTest.php

| Fixed tickets | #2165 
Fixed: when the second parameter `$options` passed to `run()` and `runLocally()`, use it to overwrite default env config.

Fix: merge $options env to context env config, with overwriting (#2165)

---

recipe/laravel.php

Add once() again command from c1309f255fc6756c70c42465f76e3d08cbeebc7a that got dropped from the v7 updated commit.

Laravel Task artisan:migrate should only run once

---

CHANGELOG.md
recipe/deploy/check_remote.php

| Fixed tickets | #2170 
Reworked the `deploy:check_remote` step, to use the `on(localhost(), ...)`, instead of relying on `runLocally`.
This has been changed, to make sure that the all functions that are being executed and are related to "local" part of the logic, are ran on the local host.
Previously in `runLocally(sprintf("%s ls-remote $opt $repository $ref", get('bin/git')));` the `get('bin/git')` would've been executed on the remote host, which could have resulted in an unexpected behaviour.
By closing all of the instructions, in the closure that is executed by the `on()` function, we are sure that the context is set to the right host.

[issue-2170] Use on(localhost(), ...) instead of runLocally in check_remote.php

---

CHANGELOG.md
test/recipe/AbstractTest.php

The unit tests would fail, when started on a non-master branch.
This was happening because the test repository has been initialized
with git default branch, whereas deploy configuration expects to
work with current git branch.
This has been fixed by adding `git checkout -B BRANCH_NAME`, right after
test repo initialization to the DeployTest setup procedure, to make sure
that the test repositoryis always in sync repo-wise with the Deployer
repository.
Fixes #2181

[issue-2181] Fix unit tests on non-master branches

---

src/functions.php
test/src/FunctionsTest.php

The `within()` function has been modified to pass-through the return value of the `$callback` function.
It is now possible to write code like:
```php
$out = within('/foo', function () {
return 'bar';
});
```
The `$out` variable will now contain the value `'bar'`.
If the callback function returns nothing, then the return of `within()` call will be `null`.
Fixes #2178

[issue-2178] within() passes through $callback return value

---

CHANGELOG.md
composer.json
composer.lock
phpcs.xml.dist
src/Configuration/Configuration.php

Refactored the code in `src/Configuration` to include type declarations for method arguments and returned values.
To make it easier to track what's left to do and to have a tool that prevents "regressions" in the future, PHP_CodeSniffer and Slevomat Coding Standard have been added.
Next, a `phpcs.xml.dist` file has been created and configured to enforce type hints for methods. For the time being, only files in the src/Configuration directory are now being watched.
To make it simpler to execute the checks, `lint` script has been added to `composer.json` to allow running checks with `composer lint`.

[issue-2187] Type declarations for src/Configuration

---

CHANGELOG.md
src/Component/ProcessRunner/ProcessRunner.php
src/Component/Ssh/Client.php
test/src/FunctionsTest.php

Added support for placeholder in the `run` and `runLocally` functions.
By passing the `vars` key with an associative array to the second
argument of `run` and `runLocally`, it is possible to use placeholders
in the command, that will be used directly in the executed command.
The placeholders should be wrapped in the command with `%NAME%`, for
instance `%foo%`. The `vars` array could be `[ 'foo' => '{{bar}}']`.
Sample:
```php
runLocally("echo '%foo%'", ['vars' => ['foo' => '{{bar}}']]);
```
will output:
```plain
{{bar}}
```
Fixes #2192

[#2192] Support for placeholders in run and runLocally

---

CHANGELOG.md
recipe/symfony4.php
recipe/symfony5.php

Just needed to change dir before executing the command.

[#2207] Symfony change dir to execute DoctrineMigrations

---

CHANGELOG.md
recipe/deploy/shared.php

Copy shared files and folder should be verbose only when deployer is run with Very verbose output `-vvv`

fixed issue #2209

---

src/Task/Task.php

this PR adds phpdoc to Task->addBefore()/addAfter(). The docs are added because I think its not obvious what the methods are doing.
e.g. a line like `task(...)->addAfter("deploy:unlock");` reads like `task` is added after `deploy:unlock` - but in fact its the opposite. `deploy:unlock` will be added after `task`.
(same argumentation for `addBefore`)
>      Please, update CHANGELOG.md by running next command:
>      $ php bin/changelog
not sure whether doc only changes should be noted in the CHANGELOG?

added phpdocs Task->addBefore() and Task->addAfter()

---

CHANGELOG.md
recipe/deploy/vendors.php

This solves https://github.com/deployphp/deployer/issues/2012 & https://github.com/deployphp/deployer/discussions/2220
I wasn't sure how to add tests for this, I could do that though.

Add composer_version to choose which composer version to install

---

docs/recipe/provision.md
recipe/provision.php
test/docker/Dockerfile
test/docker/docker-compose.yml
test/docker/scripts/provisioned-start.sh
test/e2e/ProvisionE2ETest.php
test/e2e/recipe/provision.php

Created new container using Ubuntu 20.04 as a base, for a E2E test
environment for the provision recipe.
Due to container sharing a kernel with host os, the firewall provisioning
had to be turn off during the testing procedure.

Implemented E2E tests for provision recipe

---

test/e2e/ProvisionE2ETest.php
test/e2e/recipe/provision.php

To make sure that provisioning has been properly finished, I've added simple version checks that verify that:
- nginx is present
- php is present
- php-fpm is present

Added nginx/php/php-fpm version checking to provision e2e test

---

contrib/crontab.php

`[ -f '/var/spool/cron/{{user}}' ]` requires root access and doesn't work on Debian/Ubuntu servers. Replaced it by a `crontab -l` call.

Crontab root

---

contrib/crontab.php

Makes it possible to do:
```
add('crontab:jobs', [
'* * * * * cd {{current_path}} && {{bin/php}} artisan schedule:run >> /dev/null 2>&1',
]);
```

Add config var parsing support to crontab jobs

---

contrib/cpanel.php
contrib/crontab.php
contrib/ispmanager.php
contrib/rsync.php
docs/contrib/ispmanager.md
phpstan.neon

I discovered a stupid bug in my PR (#2257). It uses a undefined variable. PHPStan can prevent those stupid mistakes. This PR adds `contrib` and `recipe` to the analysed paths. And on the fly fixes some bugs.

Let PHPStan analyze recipe and contrib folder

---

docs/api.md
src/Component/ProcessRunner/ProcessRunner.php
src/Component/Ssh/Client.php
src/Utility/Rsync.php
src/functions.php

declare `@throws` phpdoc so users know which exceptions to catch, in case they want to handle errors.
this information will help people upgrading from v6, because phpstan and friends can tell them, that they need to adjust their `catch` clauses in the recipies.
as with other phpdoc only changes, I did not add a changelog item.
great to see that we have a unique exception `RunException` for all cases. in v6 we had to catch different exceptions whether you invoke `run` or `runLocally`

added `@throws` for run/runLocally and friends

---

contrib/crontab.php
contrib/npm.php
contrib/phinx.php
contrib/yarn.php

`which` isn't POSIX compatible, `command -v` is. `locateBinaryPath` uses
the latter: https://stackoverflow.com/a/677212/2182703

Replace run('which xxx') by locateBinaryPath('xxx')

---

CHANGELOG.md
contrib/cachetool.php
docs/contrib/cachetool.md

Fixed resolving of cachetool binary.

Fixed resolving of cachetool binary and disabled support of cachetool below version 5

---

CHANGELOG.md
docs/recipe/magento2.md
recipe/magento2.php

Implements check for Magento 2 database migration needs, in order to get zero downtime deployments otherwise.
Also fixes magento 2.4 deployments due to composer autoload issue https://github.com/magento/magento2/issues/23251
Tested with Deployer 7-beta.3 and Magento 2.2 | 2.3 | 2.4 (to date only 2.3 and 2.4 are officially supported by magento).
I've checked it does not introduce so far BC breaks for these versions.

Magento 2 Zero downtime deployment

---

recipe/deploy/vendors.php

Composer installer can now take an argument to select which version channel to use: https://github.com/composer/getcomposer.org/pull/156/files
This allows for exemple to stay on major version 1 without specifying a specific Composer version

Allow changing Composer channel

---

src/Command/InitCommand.php

If it is set to null, an error will occur in other processing,
so it was initialized with an empty string.
SymfonyStyle#ask is v5 with type-hint added.
`$default` is ?string so bool is not acceptable.
https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Style/SymfonyStyle.php#L267
```sh
$ dep init
Select recipe language [php]:
[0] php
[1] yaml
> 1
Select project template [common]:
[0 ] cakephp
[1 ] codeigniter
[2 ] common
...
> 2
TypeError  in SymfonyStyle.php on line 257:
Symfony\Component\Console\Style\SymfonyStyle::ask(): Argument #2 ($default) must be of type ?string, bool given, called in phar:///src/deployer.phar/src/Command/InitCommand.php on line 71
```
- I haven't written a CHANGELOG because it's a very minor fix, but I'll write it if necessary.
Please, …

Fix dep init outside of git

---

CHANGELOG.md
docs/recipe/deploy/writable.md
recipe/deploy/writable.php

Using writable_dirs with writable_use_sudo can lead to a disaster on a server (example using /var/log instead of var/log as writable dir).

Safety to avoid modifying files outside deploy_path

---

recipe/deploy/vendors.php

- [ X] New feature?
I cannot run `php bin/changelog` because I have PHP 7.2 installed (and PHP 7.3 is required).

Local composer should take precedence over global composer

---

recipe/shopware.php

config/jwt should have chmod 600, not 755

Remove config/jwt from writable dirs list

---

CHANGELOG.md
src/Support/Stringify.php
test/src/Support/StringifyTest.php

Dump of [$input->getOptions()](https://github.com/deployphp/deployer/commit/18bdfc8bd94a8aa408f59dac1fb9daa6a8800c8c#diff-b872a77de62f6d05e055c5c2c19e0175ad4b9f4075531eee37dcba67a6d3cea8R20):
```php
array:18 [
"tag" => null
"revision" => null
"branch" => null
"option" => []
"limit" => null
"no-hooks" => false
"plan" => false
"start-from" => null
"log" => null
"profile" => null
"help" => false
"quiet" => false
"verbose" => false
"version" => false
"ansi" => true
"no-ansi" => false
"no-interaction" => true
"file" => null
]
```
```diff
foreach ($option as $value) {
+                if(is_bool($value)){
+                    $options[] = "--$name";
+                    continue;
+                }
+
$options[] = "--$name " . self::escape((string)$value);
}
```
Output of `Stringify::options()` …

Boolean options should not go through the `self::escape` function.

---

recipe/laravel.php

Fix for issue #2407 - Laravel migrations are only run on the first host due there being a `->once` on the task

Fix for issue #2407 - Laravel migrations are only run on the first host

---

composer.json
contrib/rsync.php
deploy.yaml
docs/api.md
src/Command/RunCommand.php
src/Command/SshCommand.php
src/Component/Ssh/Client.php
src/Exception/Exception.php
src/Host/Host.php
src/Support/Config/verification.php
src/Utility/Rsync.php
src/functions.php

Now, it should be not matter what default shell is used on a server: zsh, fish. Deployer will automatically switch to bash (or to user specified shell).

Refactor shell arguments escaping

---

CHANGELOG.md
docs/recipe/deploy/release.md
recipe/cakephp.php
recipe/deploy/release.php
recipe/deploy/vendors.php
recipe/flow_framework.php
recipe/laravel.php
recipe/magento.php
recipe/magento2.php
recipe/shopware.php
recipe/silverstripe.php
recipe/sulu.php
recipe/symfony.php

As discussed in PR https://github.com/deployphp/deployer/pull/2485, This PR enables users to run tasks outside a deployment by providing a new `release_or_current_path` option.
This option will always return the `release_path` if it exists and fallback to the `current_path` if it doesn't.
That way, outside of deployment, we can still run `dep my:task` and expect our task to be executed on the latest active release.
This PR replaces the use of `release_path` with `release_or_current_path` in all the custom tasks of platform-specific recipes — like laravel, symfony, etc. It also replaces the use of `release_path` in the `deploy:vendor` task, allowing users to run `composer install` on the current release if they need to.
Let me know if there are other places that would benefit from this new …

Add and use new release_or_current_path

---

CHANGELOG.md
docs/recipe/laravel.md
recipe/laravel.php

Co-Authored-By: Kundan <198781+kundancool@users.noreply.github.com>
Sorry for the bombardment of PRs haha.
I thought of another useful artisan task that is missing: `artisan:key:generate`. This can help users during their initial deployment since it is a Laravel requirement to set up the `APP_KEY`.
I saw another PR that included a similar task for Passport that generates clients IDs and Secrets. Therefore, I bundled them together here and credited the author of PR #2403 in this PR.

Add artisan tasks that generate keys

---

CHANGELOG.md
recipe/deploy/writable.php

I came across the "ACL missing" error message the other day and realised that the suggestion to fix it does not work.
According to the `dep run` signature, we should first provide the command as *one* argument before providing optional selectors.
Therefore, running **`dep run prod -- ls -la`** throws an error. ❌
But, running **`dep run 'ls -la' -- prod`** (or just `dep run 'ls -la' prod`) works fine. ✅ 
This PR, fixes the suggestion of the "ACL missing" error.
I can't seem to find any other error messages that suggest to run `dep run` but please let me know if I've missed one and I'll update it as well.
---

Fix ACL error message

---

src/Utility/Rsync.php

PR for #2497 
- [X ] New feature?
PR for rsync stats. I have target php 7.4, but if you prefer 8.0 `strpos` can be replaced with `str_starts_with`

Rsync stats config option

---

CHANGELOG.md
src/Importer/Importer.php

When providing an array of string to the `script` key inside a YAML task, each line goes through a regex that identifies whether its a `cd` command or not. That way, the following script array:
```yaml
yarn:run:prod:
script:
- 'cd {{release_or_current_path}}'
- 'yarn run prod'
```
becomes:
```php
cd('{{release_or_current_path}}');
run('yarn run prod');
```
However, the regex did not take into account that multiple commands can be run within the same line like so.
```yaml
yarn:run:prod:
script:
- 'cd {{release_or_current_path}} && yarn run prod'
```
Thus, the script array above became:
```php
cd('{{release_or_current_path}} && yarn run prod');
```
Making the task no execute anything.
This PR fixes this by adding an extra regex that looks for `\b&&\b` within the script line before wrapping …

Fix regex that identifies "cd" commands in YAML scripts

---

src/Importer/Importer.php

My bad I misused the word boundary `\b` on the regex. It simply needs to check for a whitespace.
Not sure I need a changelog for a fix of a fix right?

Fix contains multiple commands regex

---

CHANGELOG.md
composer.json
composer.lock
tests/docker/Dockerfile
tests/docker/conf/10-coverage.ini
tests/docker/docker-compose.yml
tests/docker/scripts/php-code-coverage/coverage-start-wrapper.php
tests/e2e/coverage/coverage-report.php
tests/e2e/coverage/coverage-start.php
tests/e2e/coverage/start-e2e-test.sh

The E2E docker-compose stack has been modified to include code
coverage for all scripts that are kept in /project and are not
in the exclusion list.
The start command for `deployer` container has been replaced
with a `start-e2e-test.sh` script, which will execute E2E tests,
generate a Clover report and then return the exit code of E2E test
process to make sure that CI is aware of the test result.
Whole idea for collecting E2E coverage has been inspired by the
[this][1] article. All of scripts in `deployer` container will
now start with additional wrapper-like PHP code, which checks
if the `PHP_CCOV_START_FILE` variable is present. If not,
then nothing happens, but if the variable points to a PHP file,
then that file is being included.
The `docker-compose.yml` file has …

Added support for code coverage in E2E tests

---

.gitattributes

Just added .gitattributes to exclude tests, docs from archives

add .gitattributes - exclude tests, docs from archives

---

CHANGELOG.md
src/Configuration/Configuration.php
tests/src/Host/ConfigurationTest.php

Support passing `null` as default in get()

---

docs/api.md
src/Component/ProcessRunner/ProcessRunner.php
src/Component/Ssh/Client.php
src/Support/helpers.php
src/functions.php
tests/e2e/recipe/functions.php
tests/joy/recipe/named_arguments.php
tests/src/FunctionsTest.php

As we already have `env`, let's not duplicate and remove `vars` from `run()` function.

Remove vars

---

contrib/cachetool.php
docs/contrib/cachetool.md

- remove outdated cachetool apc command (not apcu) that does not exist since 4.x,
- document web adapter example
- use release_or_current_path to be able to execute tasks outside of deployment (#2486)

Cachetool improvements

---

docs/recipe/symfony.md
recipe/symfony.php

Any standard symfony app is running cache:clear on composer install ever since.
I.e. in composer.json
```
"scripts": {
"auto-scripts": {
"cache:clear": "symfony-cmd",
"assets:install %PUBLIC_DIR%": "symfony-cmd"
},
"post-install-cmd": [
"@auto-scripts"
],
"post-update-cmd": [
"@auto-scripts"
]
},
```
This prevents cache clearing being run twice for no reason.
I've removed the task deploy:cache:warmup as it is now part of cache:clear which only runs if composer was run with --no-scripts
Since deployer is in beta, I think it's the right thing to do now.

Fix symfony cache:clear running twice on deployment

---

CHANGELOG.md
recipe/shopware.php

Currently the first step is to run bin/build.sh which builds all *ACTIVATED* themes. After this step we activate all composer-registered plugins (which in my case are all the themes) and THEN compile them. For new themes that means, that they are *NOT* build because they are activated AFTER building.
This PR fixes that and activated first and builds second.

DRAFT: First activate plugins/themes THEN build them

---

recipe/deploy/update_code.php

The $bare variable points to ".dep/repo" and not ".git/repo"

Fix typo in comment

---

recipe/deploy/release.php

This task failed every time because wie need `sudo` to clean. The code ist 1:1 copy from task `Cleaning up old releases` https://github.com/deployphp/deployer/blob/6.x/recipe/deploy/cleanup.php#L31.

Use `cleanup_use_sudo` in task `deploy:release`

---

bin/dep
docs/UPGRADE.md
docs/cli.md

Use an environment variable or setting to override the default deployer root
directory used for the runLocally() default cwd configuration.
Resolves #2628

Allow overriding deployer root directory globally

---

docs/installation.md

Fix a typo.
Added "~/" to be clear that this is in user's "Home" directory.
Added `~/.zshrc` as some user uses ZSH terminal.

Fix a little typo and improve a little clarity.

---

contrib/rsync.php
docs/contrib/rsync.md
docs/rsync.md

as discussed on #2568
Is there a way to link from `api.md` to `rsync.md`?
I would like to link `upload()` and `download()`.

docs making clear there are 2 different rsync

---

docs/recipe/symfony.md
recipe/symfony.php

Symfony doesn't use this folder by default, but this recipe still creates it (by default) on deploy. This results in an empty folder for every deployed Symfony app using the default configuration. If a developer wants to config his sessions according to the [custom save_path](https://symfony.com/doc/current/session.html#configuration) in the docs, he should add the custom path to his shared dirs himself.

Remove var/sessions as a default shared dir in the Symfony recipe

---

src/Importer/Importer.php
tests/src/Importer/ImporterTest.php

As discussed in https://github.com/deployphp/deployer/discussions/2709, I'd like to add back support for root level hidden keys in YAML files. 
I've chosen to remove the hidden keys completely after parsing because their references are already resolved during loading, so there is no point in keeping them after that. That's also the reason why I didn't change the JSON schema file that validates the contents of the input data.

feat: add support for hidden keys in yaml files

---

docs/recipe/magento2.md
recipe/magento2.php

When refactoring our Deployer 6 recipes for Magento 2 to Deployer 7, I was eventually left with this code block in all our deployment configurations;
```php
// Override default recipe tasks since we use a push-approach instead of a pull-approach
task('deploy', [
'deploy:prepare',
//    'deploy:vendors', // We run composer install in the CI pipeline
'deploy:clear_paths',
'deploy:magento',
'deploy:publish',
]);
task('deploy:magento', [
//'magento:compile', // We run bin/magento setup:di:compile in the CI pipeline
//'magento:deploy:assets', // We run bin/magento setup:static-content:deploy in the CI pipeline
'magento:config:import',
'magento:upgrade:db',
'magento:cache:flush'
]);
task('deploy:prepare', [
'deploy:info',
'deploy:setup',
'deploy:lock',
'deploy:release',
//`deploy:update_code`, …
```

Make Magento 2 recipe suitable for push strategy deployments

---

src/Component/Ssh/Client.php

In my case the string had exactly 104 chars and I got the error:
> unix_listener: [...] too long for Unix domain socket
With 103 chars it is working (I temporally changed return line to `return substr($controlPath, 0, -1)`).

Fix controlPath (length < 104)

---

recipe/magento2.php

This command fails when it is a deployment to a newly provisioned server since the current_path does not exist

Fix Magento 2 maintenance status check

---

recipe/provision/website.php

Caddy was unable to proxy request to php-fpm unix socket, after some research found missing `/` in configuration
Reference: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#examples

Fix php-fpm unix socket in provision recipe

---

recipe/provision.php

Testing deployer & the new provision recipe I noticed timeout for heavy tasks such as "Upgrades all packages" and "Installs packages".
The timeout for this tasks now is 15 minutes, WDYT?

Fix timeout for heavy tasks in provision recipe

---

docs/ci-cd.md

With this PR I tried to illustrate the deployment process, in a synthetic and simple way, through GitLab CI/CD.
The [docker image](https://github.com/debreczeniandras/deployerphp) used to run deployer is based on latest PHP 7 CLI Alpine and Composer 2.
Obviously it would be nice to have an official docker image.
Let me know what you think :wink: 

[Docs] GitLab CI/CD

---

src/Deployer.php

Currently if exception happens inside deploy.php CI will mark job as succeeded.
This PR adds exit code to run command in case it fails with an exception.

deployer should exit with error status code on exception

---

docs/recipe/laravel.md
recipe/laravel.php

Caching Routes has been recommended since the early 5.x days to improve performace or production apps.
https://laravel.com/docs/8.x/deployment#optimizing-route-loading
Reorder optimization commands to same order as Laravel docs.

Laravel: Add Route Cache to Deploy Tasks

---

contrib/sentry.php

Makes use of `git_version_command` (if defined) even when `update_code_strategy` is set to `archive`

Sentry recipe fix regarding `git_version_command` with `update_code_strategy` set to `archive`

---

recipe/provision/php.php

Update the PHP provision script.
PHP 5.4 is provided anymore by the Ubuntu LTS. Replace it by PHP 5.6.
Add PHP 8.1 as it's now released a available in default Ubuntu APT packages. Set it as the default version.

Add PHP 8.1 in the PHP provision recipe

---

docs/recipe/cakephp.md
recipe/cakephp.php

Update migration task to use current best practices.
- Skip [schema.lock file generation](https://book.cakephp.org/migrations/3/en/index.html#skipping-the-schema-lock-file-generation)
- Rebuild [schema cache](https://book.cakephp.org/4/en/console-commands/schema-cache.html) in-place
- Don't explicitly clear the cache

Update CakePHP Migration Task

---

recipe/cakephp.php

Tweak the CakePHP recipe to use the configured PHP version instead of the target system default. Useful when multiple PHP versions installed in the deploy target.

CakePHP recipe, use the configured PHP version

---

recipe/deploy/writable.php

Only add the the remote user to setfacl command if it exists as an os user.
Based on this discussion:
https://github.com/deployphp/deployer/discussions/2787

Don't add remote user to setfacl command, if it doesn't exist as an os user

---

docs/recipe/symfony.md
recipe/symfony.php

This pull request add the Doctrine mapping files validation (*with `--skip-*` option*) as a (*possible*) deploy task.

Add  Doctrine mapping files validation

---

docs/getting-started.md
docs/recipe/provision.md
recipe/provision.php

Hello,
This is to address issue #2939 by adding a tip on the documentation and more info on the warning banner when provisioning a server.
I'm not sure if the code block will display correctly inside a tip block, or event if a tip block is what you want. If that's an issue, how would you like this info to be displayed?
(done)

Update doc provision as root

---

docs/hosts.md

Fix `host` examples

---

docs/recipe/magento2.md
recipe/magento2.php

Hoping this can make it into the main repo, this addresses #2936, allowing users to disable zero-downtime deployment. The flag defaults to allowing it; users would have to set it in their own `deploy.php` file, and then be required to enable/disable maintenance mode on their own.
This also adds `.maintenance.flag` to the shared files array.

Magento2: allow non-zero-downtime deployment

---

docs/recipe/deploy/update_code.md
recipe/deploy/update_code.php

Fixes #2570 
This feature adds an option to specify a sub directory in the repository of the project. This can be useful when you only want to deploy a single folder in the repo.
An example use case would be a repository with a separate frontend and backend, each living in their own folder.
When no `sub_directory` is specified, the entire repository will be deployed. Works only when `update_code_strategy` is set to `archive`, which is the default option.

Issue 2570: Add an option to deploy only a sub-folder of the repository

---

src/Collection/Collection.php
src/Task/GroupTask.php
src/functions.php

Implemented basic version of replacing tasks, fixes #2878

---

src/Command/SshCommand.php

Hi everybody ! 
I'm unable to deploy on Windows ( 10 or 11 ). I always get this error 
```bash
php .\vendor\bin\dep ssh
The specified path was not found.
The specified path was not found.
```
The only thing I found is to change simple quote to double quote for ssh command. 
It works on Windows but fails on MacOS. That's why I  check PHP_OS constant.
My tests on Windows were on real machine with Windows 10 and virtual machine on Windows 11. The results are sames. 
Thanks a lot for your review !

Fix ssh command to work on Windows

---

contrib/npm.php
docs/contrib/npm.md

If a node_modules is already present, it will be automatically removed before npm ci begins its install.
See https://docs.npmjs.com/cli/v8/commands/npm-ci

Don't copy node_modules because it will be removed

---

src/functions.php

The ConfigurationException in the get() function of class Config will never be reached by the get() in functions.php
So if the key doesn't exist always null is returned.

Check func_num_args() in get()

---

src/Importer/Importer.php
tests/src/Importer/ImporterTest.php

Although it seems to be a new feature, I think this could be treated as a bugfix.
I wanted to extend (not override) the `shared_dirs` configuration from YAML file, but it occurred that the `Importer` uses the `set()` function instead of `add()`. Thus, I wanted to extend the class, because the methods are protected and not private, but it was not possible because it uses `self::` instead of `static::`.
```yaml
config:
shared_dirs:
- my_extra_shared_folder
```
This pull requests makes the `Importer` class extendable, for example:
```php
class ExtendedImporter extends \Deployer\Importer\Importer
{
protected static function config(array $config)
{
foreach ($config as $key => $value) {
add($key, $value);
}
}
}
ExtendedImporter::import('deploy-hosts.yml');
```

Make the importer extendable

---

recipe/laravel.php

This adds event caching to Laravel apps.  This does not appear to harm Laravel apps with event discovery disabled but will speed up applications that do use it.  Feature first introduced with Laravel 5.8.9 and added as a stand alone task in deployer https://github.com/deployphp/deployer/commit/a6ff2eb4c6eb87052f94fdf9d4f9c4aad42d7c9c
https://laravel.com/docs/9.x/events#event-discovery-in-production
> In production, it is not efficient for the framework to scan all of your listeners on every request. Therefore, during your deployment process, you should run the `event:cache` Artisan command to cache a manifest of all of your application's events and listeners. 
Running on a Laravel application without custom `app/events` or `app/listeners` simply creates a manifest in …

Add artisan event:cache to Laravel deployment task

---

composer.json
composer.lock

Don't fake the PHP version available from the environment.
Closes #2927.

Remove platform from Composer config

---

.github/workflows/release.yml
deploy.yaml

This is a new release process for Deployer which will merge deployer/dist & deployer/deployer. 
I got too many requests to update Symfony & PHP.

New release process: publish deployer.phar in a tag

---

docs/recipe/magento2.md
recipe/magento2.php

- [ - ] New feature?
- [ - ] Docs added?

DD#0000: feat: Added configurable themes to Magento2

---

docs/recipe/deploy/lock.md
recipe/deploy/lock.php
tests/legacy/DeployTest.php

…lock on the deployment
- [ - ] New feature?
- [ - ] Tests added?
- [ - ] Docs added?

Lock update

---

docs/recipe/contao.md
recipe/contao.php

Since Contao 4.13 the `contao:migrate` performs the automatic database backup task, so I think we should enable `--with-deletes` flag by default.
/cc @richardhj

Add --with-deletes flag to contao:migrate task

---

recipe/deploy/update_code.php

The bug is described in detail in issue #3137.

Use correct Git ref spec when `sub_directory` is specified.

---

src/functions.php

To clarify which task is causing the exception.

chore: add task name to replace exception message

---

recipe/contao.php

This changes the definition of `{{bin/console}}` parameter to always use PHP version defined by user. It is consistent with the way it's done in Symfony recipe, which this recipe is based on.
Fixes minor bug, where `contao_version` task fails to run (can be verified by running `deployer config`, for example).

Fix definition of {{bin/console}} parameter in Contao recipe

---

docs/tasks.md

Typo in docs "oncePerNode"

---

docs/UPGRADE.md

Today on https://deployer.org/docs/7.x/UPGRADE

fix(typo): Missing backtick on deploy:cleanup command in upgrade.md

---

recipe/provision.php

Fixes this problem with Caddy installation:
```
Err:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is not signed.
```
[https://caddyserver.com/docs/install#debian-ubuntu-raspbian](https://caddyserver.com/docs/install#debian-ubuntu-raspbian)

Fix Caddy install

---

docs/recipe/magento2.md
recipe/magento2.php

It will fix following Zend exception after successful deployment:
Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/path/to/www/releases/7/var/page_cache" is not writable in /path/to/www/releases/7/vendor/magento/zendframework1/library/Zend/Cache.php:209
This exception does not occur on every environment, as always, it depends on PHP pool user/group (default www-data or owner of project directory).

var/page_cache as writable_dirs

---

docs/UPGRADE.md

The title of the page was misleading, it shown the version on the left menu:
> ![image](https://user-images.githubusercontent.com/2071331/173890801-c7f8a470-4985-4268-80bb-742cada0b384.png)
But the page list upgrades for other versions.

UPGRADE: remove version form title

---

contrib/crontab.php

Concerned issue: https://github.com/deployphp/deployer/issues/3049

Generate random crontab tmp path

---

recipe/shopware.php

This was a temporary workaround and the version with the fix was released nearly a year ago. There were multiple security updates in between, therefore running the old version is negligent anyway. In my opinion this can be deleted.

Removed temporary workaround as it is for a version which is a year old

---

recipe/deploy/release.php

Uses the [`escapeshellarg()`](https://www.php.net/escapeshellarg) function to wrap the JSON with single quotes and escape all other single quotes present in the JSON string.  Closes #3260.

Escape metainfo to prevent bash syntax errors

---

recipe/laravel.php

As discussed [here](https://github.com/deployphp/deployer/discussions/3356) with @peterjaap, database tasks could be omitted if the .env file is missing on the Laravel recipe.
Before:
- `php artisan migrate` => `Your .env file is empty! Skipping...` ✅ 
- `php artisan migrate:rollback` => Crashes the deploy ❌ 
After:
- `php artisan migrate` => `Your .env file is empty! Skipping...` ✅ 
- `php artisan migrate:rollback` => `Your .env file is empty! Skipping...` ✅ 
Let me know if you need me to add anything regarding documentation or tests.

Laravel recipe: Skip database tasks if .env is missing

---

contrib/cloudflare.php
docs/contrib/cloudflare.md

This commit 
* adds extra support for `api_token` config to be used. This has been tested locally.
* `domain` config is only required if `zone_id` is not provided, hence code & documentation have been updated accordingly
> Cloudflare authorization is also supported by API Tokens, which is considered as a better practice compared to API Keys.
Signed-off-by: AbhishekKr <abhikumar163@gmail.com>

Add Cloudflare API Token support for auth; make domain optional if zone_id is provided

---

recipe/laravel.php

One of base command to publish your application with Horizon
```
$ php artisan horizon:publish
Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]
Publishing complete.
```

Laravel recipe: Add horizon publish command

---

contrib/cachetool.php

Small QoL change. The current recipe will always download version 7.0.0 of Cachetool, which is compatible with PHP 7.3 and up.
For future releases we could bump to 8.0.0 and 9.0.0 (see https://github.com/gordalina/cachetool#compatibility for the exact versions). Only <8.1 and >8.1 are included in this PR because the v8 branch only supports ^8.0.

Select the appropriate cachetool url based on the PHP version

---

contrib/newrelic.php
docs/contrib/newrelic.md

For EU region the API endpoint is different and users should be able to change it otherwise deploy notifications don't get saved to their projects.
https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/

moved newrelic endpoint to config and used it when posting to api

---

docs/recipe/magento2.md
recipe/magento2.php

`pub/static/_cache` should be declared as `shared_dir`, so it's possible to mount it between different app-servers
in a multi host setup.
Example:
- run Magento with two app-servers (app-a / app-b)
- route all admin request to app-a
- cached css files will be generated on app-a and app-b
- observe 404 responses for files of `pub/static/_cache` directory

add pub/static/_cache as shared_dir

---

.github/workflows/test.yml
composer.json
composer.lock

Replaces https://github.com/deployphp/deployer/pull/3401
Using @Konafets' work and updating the composer.lock file
Closes https://github.com/deployphp/deployer/issues/3399 and https://github.com/deployphp/deployer/pull/3401

Make Deployer work with PHP 8.2

---

.github/workflows/check.yml
.github/workflows/docs.yml
.github/workflows/sync.yml
.github/workflows/test.yml

This PR fixes the following warning
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix set-output command is deprecated and will be disabled soon

---

.github/workflows/test.yml

The unmaintained version uses Node12.

Replace unmaintained satackey/push-prebuilt-action by a maintained fork

---

.github/workflows/sync.yml

This PR fixes the following warning
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: EndBug/add-and-commit@v7. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Suggested long term solution: replace this action by git commands used directly to minimize maintenance

Fix NodeJS 12 warning: update EndBug/add-and-commit action

---

recipe/deploy/writable.php

Updating this task to use release_or_current_path (from #2486)  will allow the writable task to be used outside of deployment.
This should probably be done for all tasks after the change in #2486 as it will now be expected to work by others using the software and reading #3337, It has also been done for some more tasks in #2604.
For now, I don't wan to touch more parts of the code without knowing if it will break something else. This does it for `writable` only.

update writable deploy recipe to use release_or_current_path

---

docs/UPGRADE.md

I noticed this sentence while upgrading a project and think it sounds not clear enough. What do you think?

Update Upgrade instructions

---

docs/recipe/magento2.md
recipe/magento2.php

- Fix 1. Add `-p` parameter to mkdir command for `{{artifact_path}}` could be configured with multiple folders such as build/artifacts
- Fix 2. `run()` -> `runLocally()` – The `{{artifact_dir}}` is used to keep artifacts archive file. It should be called at CI server only and not at target server. Then the task `artifact:upload` uploads this file at target server host under `{{release_path}}`. It is not needed to have `{{artifact_dir}}` at target server.

Magento: Fix artifact_path generation

---

docs/selector.md

As the `env` config options is expected to be an array, not a string, the supplied example is throwing errors. This syntax checking of the `env` variable seems to only happen in the YAML config syntax, not with the php config.

docs(selector): correct env config option to array

---

docs/ci-cd.md

While using the GitHub action example to setup our deployment flow, I noticed the PHP version being outdated & a `composer install` step missing.

docs(github-action): improve & update

---

src/Component/Ssh/Client.php

When using [deployphp/action](https://github.com/deployphp/action), any config option defined in the workflow is supplied to `deployer` as a string. 
This breaks the process in the case of timeout options, because `Symfony\Component\Process\Process::setTimeout` and `Symfony\Component\Process\Process::setIdleTimeout` expect numeric values.

Prevent type errors when defined timeout options are not numeric

---

docs/recipe/shopware.md
recipe/shopware.php

- [ x ] Bug fix: **Shopware bin/console calls with default bin/php and not with {{bin/php}}**
I was running the recipe with {{bin/php}} = /opt/local/bin/php8.2 but my default cli version is php7.4 the deployment stopped caused of the wrong php version by calling bin/console directly.

Fixed bin/console calls in shopware recipe

---

recipe/shopware.php

The new [Shopware template](https://developer.shopware.com/docs/guides/installation/template) does not have a `bin/build.sh` file anymore. The missing executable executed `composer install` and `bin/build-js.sh`. Since requiring the new Symfony flex recipe requires running `composer` manually, we just execute `bin/build-js.sh` now.
This could be a breaking change for some users. Don't know if you want to state that somewhere or allow a way to restore the old behavior via flag? (Although one can just override the `sw-build-without-db:build` task anytime)

Shopware Flex has no `build.sh` anymore

---

contrib/ms-teams.php
contrib/slack.php
contrib/telegram.php
docs/contrib/ms-teams.md
docs/contrib/slack.md

Some contrib recipes would fail silently if there was no required config configured. Now the following throw a warning which I believe contributes to a better user experience.
* `contrib/ms-teams.php`
* `contrib/telegram.php`
* `contrib/slack.php`

Teams, Telegram, Slack contrib recipe no longer fails silently if no webhook is configured

---

docs/recipe/common.md
recipe/common.php

`recipe/common.php` currently does not define a deploy task and is the only recipe that's missing it.
Newcomers may stumble over this behavior, as the documentation asks you to run `dep deploy` as one of the first steps.
This PR fixes this.
It's compatible with recipes that are based on `common`, as overwriting tasks is allowed (e.g. common > symfony > contao).
Note: It appears that this task was previously defined (see #296).

Added missing deploy task to recipe/common

---

src/Executor/Messenger.php

The current `section_end` markers for GitLab CI do not conform to the syntax described in the [documentation](https://docs.gitlab.com/ee/ci/jobs/#custom-collapsible-sections). Instead of the current timestamp, the text line includes the elapsed task time in a format (e.g. `1s 884ms`) that is not caught by the [regex that GitLab uses](https://gitlab.com/gitlab-org/gitlab/-/blob/4ea0cb1a966167effe1625bd89e7be9c24405911/lib/gitlab/regex.rb#L422).
This issue in practice remains unnoticed until additional output is supposed to be displayed in the job output after the Deployer process has finished. In this case, any additional output is hidden inside the collapsed section of the last Deployer task.

Fix collapsible section's end markers in GitLab CI job output

---

composer.json
composer.lock
docs/recipe/magento2.md
recipe/magento2.php

Magento 2: Cache key id prefix

---

recipe/magento2.php

Fixes a bug introduced with the PR #3456
When the option "from_repo" is enabled (magento2 recipe), the tar artifact is not generated properly.
It is generated with the following structure:
```
artifacts/
repo/
[magento project]
```
Whereas it should be:
```
./
[magento project]
```
This PR fixes this issue.
The artifact is now generated correctly with or without the option enabled.

Fix artifact file generation when "from_repo" option is enabled

---

contrib/supervisord-monitor.php
docs/contrib/supervisord-monitor.md

Just fixes a few syntax typos on one of the pages in the docs

fix(docs): typos in supervisord-monitor example

---

recipe/shopware.php

- Bug fix: the theme is missing on deployed version. Compiling the theme in the sw:deploy task fixes it. Another fix: in CI systems there is no way to compile the theme locally since a database connection is needed. Adding the theme compile skip option at the build-js.sh fixes it as well.

changes for using latest shopware flex template

---

docs/recipe/deploy/rollback.md
recipe/deploy/rollback.php

**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix
**What is the current behavior?** (You can also link to an open issue here)
Typos in the documentation for the `rollback` command (https://deployer.org/docs/7.x/recipe/deploy/rollback#rollback_candidate).
**What is the new behavior (if this is a feature change)?**
Typos fixed
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
**Other information**:
-

Fix typo in `rollback.php`

---

recipe/craftcms.php

This is to make two small changes to the Craft CMS recipe to add the .env file to shared & remove the writable config which causes issues for our own deployments. Since no other recipes add writable config I presume this is unnecessary.
Once merged in: 

Add .env to shared, remove unecessary writable config

---

bin/build

fix completion templates skipping

---

src/Command/SshCommand.php

SshCommand: Fix host selection

---

recipe/magento2.php

- [] Bug fix
Use `{{bin/magento}}` instead `{{current_path}}/{{magento_dir}}` to build Magento static content.

use {{bin/magento}} to build static content

---

composer.json
composer.lock
docs/recipe/magento2.md
recipe/magento2.php

DD#0000: feat: Move var-exporter into main requirements

---

src/Executor/Messenger.php

According to this https://docs.gitlab.com/ee/ci/jobs/#custom-collapsible-section, we need to provide a unix timestamp in seconds, not in milliseconds.
This is a reduced raw output of a deployer-job i just ran:
```
[32;1mSkipping Git submodules setup[0;m
section_end:1691389375:get_sources
[0Ksection_start:1691389375:download_artifacts
[0K[0K[36;1mDownloading artifacts[0;m[0;m
[32;1mDownloading artifacts for build_release_frontend (431863)...[0;m
...
section_end:1691389376:download_artifacts
[...]
[0Ksection_start:1691389377467:1691389377467[collapsed=true]
[0Kdeploy:setup
[0Ksection_end:1691389379794:1691389377467
[0K
```
As you can see, the output generated by gitlab itself has 10-digit-timestamps, but the output generated by deployer is based on millis. This leads to …

Fix output of elapsed time in section markers in gitlab

---

docs/recipe/shopware.md
recipe/shopware.php

This PR will add the registering of new themes and scheduled tasks during deployment to the Shopware recipe

Shopware: Register new themes and scheduled tasks during deploy

---

src/Utility/Rsync.php

Filter out empty rsync command arguments

---

docs/recipe/typo3.md
recipe/typo3.php
src/Deployer.php
src/Executor/Master.php
src/Task/GroupTask.php
src/Task/Task.php

* Update recipe for TYPO3 v12
* Allow tasks to be added before or after a task in a given task group
* Allow to hide spinner to enable interactive tasks on be run on the remote server

[TASK] Update TYPO3 recipe

---

docs/hosts.md

```bash
Recipes documentation updated.
On branch style/docs/hosts
Your branch is up to date with 'origin/style/docs/hosts'.
nothing to commit, working tree clean
```

style(docs/hosts): correct included words in inline code styling

---

contrib/crontab.php
docs/contrib/crontab.md

Rewrite of the crontab contrib recipe. It creates a 'section' in the crontab without modifying the original crontab (before the whole crontab was wiped). If the cronjobs are modified it only touches the section. This removes the need to remove old 'unused' cronjobs when changing the command.

Crontab: Rewrite the crontab recipe to work with sections

---

docs/recipe/shopware.md
recipe/shopware.php

Reverse 4c6914596faa6809595a18e4c0b6a17396158e86 and improve on #3586; see discussion in the issue for more information.

Reverse 4c6914596faa6809595a18e4c0b6a17396158e86 and improve on #3586

---

src/functions.php

Prevents line breaks that might be outputed in `run` return to break condition.
I had a case with WP CLI (using [remote SSH features](https://make.wordpress.org/cli/handbook/guides/running-commands-remotely/#using-before_ssh-hook-on-client-machine)) where the output of run contains a line break that makes the test command fail whereas it shouldn't have.
Basically, instead of getting `+accurate`, I got `\n+accurate` which [makes the test](https://github.com/deployphp/deployer/blob/6611816c89524433bd5eb592457a62c3c8ee96f5/src/functions.php#L480) evaluate to `false`.

Fix test function

---

docs/getting-started.md

This pull request fixes a factual error in the current getting started documentation.
The current version is recommending setting a **reverse** DNS record for a server in order to allow to SSH into it using a domain name instead of an IP address. However, this is the whole purpose of a **DNS record** * (without "reverse").
DNS translates a hostname ("domain") to an IP address (which is what we want here).
Reverse DNS does the exact opposite: Translating an IP address back to a hostname which is e.g. required for running a mail server but is completely unrelated to reaching a server by its hostname/domain.

Removing wrong information regarding reverse DNS

---

docs/recipe/contao.md
recipe/contao.php

This PR fixes default values of config variables `contao_version` and `symfony_version`.
**Context:**
When installed, Contao overrides output of Symfony's console command `bin/console --version`, so that it returns Contao's version instead of Symfony's. The only way the get Symfony's version in this case is to run `bin/console about`.
In addition, `bin/console contao:version` command is deprecated since Contao 4.13 (current LTS), and no longer works in Contao 5.2 (current latest). Thus, in Contao 4.13 both `console --version` and `console contao:version` show Contao's version and neither of them shows Symfony's. In Contao 5.2, `console --version` shows Contao's version, and `console contao:version` fails.
This PR fixes it by parsing output of `bin/console --version` into `contao_version` …

Fix version variables in Contao recipe

---

contrib/crontab.php
docs/contrib/crontab.md

This makes it possible to overwrite the bin/crontab variable to edit crontab for other users.
e.g.
```php
set("crontab:use_sudo", true);
set("bin/crontab", function () {
return which('crontab') . " -u www-data";
});
```

Crontab: allow sudo with crontab:use_sudo option

---

recipe/provision/website.php

Fixes https://github.com/deployphp/deployer/issues/3542

Switch to owner change instead of shh user change

---

recipe/provision/Caddyfile
recipe/provision/website.php

- Move `Caddyfile` in to separate file to increase readability.
- Make use of `{{vars}}` instead of `$vars` (`realpath` had to be set for `deploy_path`)
This might be the first step for a better configurable `Caddyfile` in the future.

Move Caddy file in to separate file

---

recipe/provision/php.php

Default is `2M`, which isn't enough when uploading documents or video's. Not sure how applicable this setting is for the cli, but I added it for consistency.

Increase `upload_max_filesize` to 128M

---

docs/recipe/shopware.md
recipe/shopware.php

Refactoring the `getPlugins` function to not parse regular commandline output anymore, instead use the --json flag `plugin:list`. Refactoring 'sw:plugin:update:all' to not upgrade every installed plugin, but every installed plugin that in fact is upgradable.

refactor(shopware): Optimize `getPlugins` to use json output

---

recipe/deploy/info.php

I always find myself adding a task to just show the release name.
Why not add it to the built-in `deploy:info` task?

Add release name to deploy:info

---

.github/workflows/check.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/sync.yml
.github/workflows/test.yml

Fixes most of "Node.js actions are deprecated" warnings (only 1 remaining for jpribyl/action-docker-layer-caching which is not maintained anymore)

Update actions/checkout and actions/cache to v4

---

src/Utility/Rsync.php

Passing an empty argument causes error during the `for` loop of `$command` array. `upload('source', 'destination', ['flags' => '']);`
This is a fix for bug introduced in #3683

Fix the Rsync command filter to rekey the array

---

recipe/shopware.php

Shopware has switched to `.env.local` for modifications since [6.5.0.0](https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/notes-to-the-APP-URL), whereas the `.env` provides sane defaults now.
I guess this can break old setups, depending on how `deploy:update_code` was implemented. Since the basic recipe is not working anyway at the moment, I guess it can be changed though…

Shopware has switched to `.env.local`

---

recipe/provision/nodejs.php

I was still using the old LTS version of NodeJS, I left it updated to the new LTS 20.x.

Update nodejs to LTS version

---

docs/recipe/magento2.md
recipe/magento2.php

`$ php bin/docgen`
Try #3779 again with changes in the correct file according to: https://github.com/deployphp/deployer/pull/3779#issuecomment-1946738715 :)

docs(recipe/magento2): fix typo in conccurent

---

bin/build
docs/recipe/provision/website.md
recipe/provision/website.php

Hotfix/v7.4.0: Fixes caddyfile and realpath errors in provision:website

---

docs/recipe/craftcms.md
recipe/craftcms.php

Added the `--interactive=0` flag to each command, with an option to not add it.
Added new `cache-clear`, `gc`, `setup/app-id` and `setup/security-key` tasks.
Removed the `try {} catch` for any `craft()` command. 
This resulted in Deployer thinking a deploy was successful when it was not.
Documented options for the `craft()` command

Update Craft CMS deploy recipe

---

docs/avoid-php-fpm-reloading.md

Avoid php-fpm reloading in Apache

---

.github/workflows/check.yml

This PR correct the step name from `Run test suite` to `Run PHP_CodeSniffer` when running PHP_CodeSniffer.
It is expected to be a copy-paste left over originating from `.github/workflows/test.yml`. Given this code doesn't touch any application logic there doesn't seem to be a need to regenerate the documentation.

Correct step name

---

src/Utility/Httpie.php

Google will be retiring goo.gl redirects, so go ahead and point directly at php.net.

Change goo.gl URL to php.net

---

recipe/codeigniter4.php

- Introduce `recipe/codeigniter4.php` with default configurations and tasks.
- Define shared directories and files, writable directories, and log files.
- Implement `spark` function to run CodeIgniter 4 commands with various options.
- Add tasks for cache, config, environment, filters, language, namespaces, php.ini, routes, encryption key generation, optimization, publishing, database operations, and housekeeping.
- Include a main deploy task that prepares, installs vendors, optimizes, migrates, and publishes the project.
Inspire from laravel recipe.

feat: :sparkles: Add deployment recipe for CodeIgniter 4

---

docs/recipe/cakephp.md
docs/recipe/codeigniter.md
docs/recipe/codeigniter4.md
docs/recipe/contao.md
docs/recipe/craftcms.md
docs/recipe/drupal7.md
docs/recipe/drupal8.md
docs/recipe/flow_framework.md
docs/recipe/fuelphp.md
docs/recipe/joomla.md
docs/recipe/laravel.md
docs/recipe/magento.md
docs/recipe/magento2.md
docs/recipe/pimcore.md
docs/recipe/prestashop.md
docs/recipe/silverstripe.md
docs/recipe/spiral.md
docs/recipe/statamic.md
docs/recipe/sulu.md
docs/recipe/symfony.md
docs/recipe/typo3.md
docs/recipe/wordpress.md
docs/recipe/yii.md
docs/recipe/zend_framework.md
src/Documentation/DocRecipe.php
src/Executor/Messenger.php

The Gitlab CI output now shows this;
I then have to expand that task output, to see the second task;
..etc etc.
This is very annoying to reach the end with 30+ tasks.
Apparently the collapsed=true is not needed to make a section, which is by default collapsed and causes this behavior. Removing it should fix this issue.

Remove collapsed true from Gitlab CI output

---

docs/selector.md
src/Host/Host.php
src/Selector/Selector.php
tests/src/Task/ScriptManagerTest.php

The existing solution does not allow OR conditions in the scope of single label value in the select query. 
The following example is only possible:
```
task(...).select('stage=prod & role=web, stage=qa & role=web')
```
In other words, only the following conditions could be defined in the query:
```
(condition1 and condition2) or (condition3 and condition4)
```
Example:
```
stage=prod & role=web, stage=qa & role=web, stage=qa & role=db, stage=prod & role=db
```
But in most cases, we need the following query:
```
(condition1 or condition2) and (condition3 or condition4)
```
Example:
```
stage=prod|qa & role=web|db
```
The PR is adding that support. 
```
host('prod.example.org') 
->set('hostname', 'example.cloud.google.com')
->setLabel( 'stage' => 'prod' 'role' => ['build','web','redis'] ]) …
```

add support of multiple values in host label

---

docs/recipe/magento2.md
recipe/magento2.php

https://github.com/deployphp/deployer/pull/3658 broke zero downtime deployment in Magento 2. This PR fixes it. See comments in https://github.com/deployphp/deployer/pull/3658 for an explanation about the issue.

Fix Magento 2 Zero Downtime Deployment

---

src/Host/Host.php

This PR adds a `setShellPath` method to the `Host` class, allowing users to define a custom shell path more easily when using Deployer.
When using MySecureShell or other shell environments that do not support the `-l` option, Deployer's SSH command fails. By providing a dedicated method for setting the shell path, users can work around this issue without needing to manually override the shell path in the configuration.
- Adds `setShellPath` and `getShellPath` methods to the `Host` class.
- Allows users to set a custom shell path via the `deploy.php` configuration file.
```php
host('production')
->setHostname('your-hostname')
->setRemoteUser('your-user')
->setIdentityFile('~/.ssh/your-key')
->setShellPath('/bin/bash');  // Sets the shell path to /bin/bash

Add setShellPath method to customize shell path in Host class

---

contrib/cachetool.php

Cachetool has newer release. This PR updates the version number. It would be also possible to use "https://github.com/gordalina/cachetool/releases/latest/download/cachetool.phar" for the latest version. See https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

Update cachetool to latest version

---

Dockerfile
docs/ci-cd.md

More in https://github.com/deployphp/deployer/discussions/3924#discussioncomment-11014453
- Fix typo in docs, where `v` was missing in image version.
- Edit Dockerfile. `dep` command is now available and default as entrypoint.

Rename docker bin name to /bin/dep

---

docs/recipe/deploy/writable.md
recipe/deploy/writable.php

Managing writable files owned by the `http_user` can be challenging in environments where multiple auxiliary users need editing access. A common solution is to use `setfacl` to assign appropriate permissions for specified groups.
This PR enhances the `acl` mode in the `deploy:writable` task by introducing a new option: `writable_acl_groups`. This option allows you to specify a list of group names that will be passed to all `setfacl` commands in the `deploy:writable` task.
The `writable_acl_groups` option defaults to `[]`, ensuring full backward compatibility without breaking existing implementations.
Given the following settings:
```php
// Existing options
set('writable_mode', 'acl');
set('writable_recursive', true);
set('writable_dirs', ['dummy_dir']);
set('remote_user', 'cluster-user'); …
```

Added `writable_acl_groups` option to acl mode in `deploy:writable`

---

recipe/laravel.php

Just renames the wrong command.

Fix tasks to start/restart Laravel Reverb

---

recipe/pimcore.php

In order for the objects to be created correctly, ‘pimcore:build:classes’ must be executed
#3448
Bug fix pimcore build classes

Bugfix pimcore build classes

---

recipe/shopware.php

The Shopware recipe currently hardcodes the `current` symlink. This creates issues for users who use a different symlink name, such as `live`.
The `current_path` variable is already defined, so it should be used to provide flexibility and avoid hardcoding the symlink name.

Using `current_path` instead of hardcoding `current`

---

docs/UPGRADE.md

UPGRADE.md: fix typo

---

contrib/chatwork.php
docs/contrib/chatwork.md

since deployer 7.x the `success` task is named `deploy:success`

remove deployer 6.x leftovers

---

recipe/deploy/update_code.php

when upgrading from v6 to v7 - in which the `repository` config was not necessary, the `update-code` task might be invoked without this expected config beeing set.
report a proper exception for better DX

Report missing repository config in update-code task

---

recipe/shopware.php

Since some newer Shopware version, the `theme:dump` command is interactive by default and since 6.6.9.0, a non-interactive parameter was added: https://github.com/shopware/shopware/blob/v6.6.9.0/changelog/release-6-6-9-0/2024-11-21-theme-dump-interactive-part-should-be-optional.md
Without `-n`, the deploy fails.

Update theme:dump with new non-interactive option

---

recipe/provision/Caddyfile

I was kind of shocked to see that compression was not enabled in the server by default. Seems pretty important to me.

Added: encode responses in the file server

---

.github/workflows/lint.yml
src/Component/PharUpdate/Update.php
src/Documentation/DocGen.php
tests/legacy/recipe/named_arguments.php

adds a new Github Action workflow via lints against PHP 7.x to prevent problems like https://github.com/deployphp/deployer/discussions/3976 which got fixed in https://github.com/deployphp/deployer/commit/f1f7b6169a1b48d7f715a10e8eb8323703cb9ab7
the newly added check skips the following files, as these currently contain PHP8+ only syntax:
```
Script parallel-lint handling the __exec_command event returned with error code 1
Error: Parse error: syntax error, unexpected 'o755' (T_STRING), expecting ')' in src/Documentation/DocGen.php on line 311
Error: Parse error: syntax error, unexpected 'o755' (T_STRING) in src/Component/PharUpdate/Update.php on line 104
Error: Parse error: syntax error, unexpected ':', expecting ')' in tests/legacy/recipe/named_arguments.php on line 8
```

Lint sources on PHP 7.x via Github Action

---

recipe/magento2.php
src/Support/helpers.php
src/functions.php

Add array_is_list polyfill as requested in https://github.com/deployphp/deployer/discussions/4007#discussioncomment-12145348.

Add array_is_list polyfill for backward compatibility

---

src/Executor/Server.php

This should fix the issue described in: https://github.com/deployphp/deployer/discussions/3981
It also simplifies the code a bit.
I had this issue when the response get too big just before the deploy finishes. For example if you keep 10 or more releases. Then the read terminates after the first pass becuase there are two line breaks after the headers and before the payload JSON starts and thus the `strpos($request, "\r\n\r\n")` is triggered after the first iteration even if there are more data to read.

 Fix issue where stream read is terminated prematurely

---

contrib/crontab.php
docs/contrib/crontab.md

Addresses feature proposed in #4031. Adds a new task that removes all host-specific cronjobs from the remote crontab.

Add crontab:remove task to contrib/crontab.php

---

recipe/deploy/release.php

Fix performance of task `releases` by checking `cat releases/$release/REVISION` only for existing releases and not all past releases stored in `releases_log`.
A real example data to compare results.
In `releases_log` there are 160 releases logs.   
In `releases_list` there are 5 releases folders.
Before fix: 57 seconds.
After fix: 7 seconds.

Fix performance of task "releases"

---

docs/recipe/shopware.md
recipe/shopware.php

We've seen a few complaints about how Shopware 6.6+ appeared to have dropped support for http:cache:warm:up. This is why we've added conditional logic to check the current shopware version, very similar to how Magento's version check works [as can be seen here](https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L111).
The change in Shopware was loosely mentioned here: https://github.com/shopware/shopware/blob/932d232e999f06cf340ed00708047b9721b253b0/UPGRADE-6.6.md?plain=1#L1035

Disable the http:cache:warm:up step for Shopware 6.6+

---

contrib/crontab.php
docs/contrib/crontab.md

Fix #4036: Escape shell argument when setting remote crontab

---

recipe/provision/php.php

`composer.json` can contain: `"php": "^8.2.0"`, in this case `php8.2.0` will be used for provisioning, and `php8.2.0-*` packages don't exist.
Also added `8.3` in the choices (as it was already the default)

Php composer parsing

---

recipe/provision.php

On a fresh VM, VPS or LXC, Ubuntu 24 doesn't have `gpg`, `add-apt-repository` and `curl`.
Shouldn't introduce any breaking change.

`add-apt-repository` pre-requisites

---

docs/recipe/shopware.md
recipe/shopware.php

Shopware has decided to make their theme compilation atomic: https://developer.shopware.com/docs/resources/references/adr/2023-01-10-atomic-theme-compilation.html
This means, on each deployment, during the execution of `theme:compile` (when building remotely, code is [here](https://github.com/deployphp/deployer/blob/master/recipe/shopware.php#L114-L118)), the storefront page is broken, because the new theme files only exists in an unreleased release, until `deploy:publish` happens.

Shopware recipe: Share theme folder for atomic themes

---

docs/recipe/laravel.md
recipe/laravel.php

**Problem**
With certain setups the default path for artisan does not resolve to the correct directory (eg. monorepo with laravel + another application).
**Solution**
This PR adds the possibility to set a custom path to `artisan`, with a fallback to the default path if no custom path is defined.
**Notes**
This PR is somewhat similar in nature to https://github.com/deployphp/deployer/pull/3772 but aims to provide an easier way of adjusting the path

Feature - Laravel - Customizable artisan path

---

docs/recipe/laravel.md
recipe/laravel.php

I have added the following missing horizon tasks, to laravel recipe:
- `artisan:horizon:supervisors` : Lists all of the supervisors
- `artisan:horizon:clear-metrics`: Deletes metrics for all jobs and queues
- `artisan:horizon:snapshot`: Stores a snapshot of the queue metrics

Add missing horizon tasks

---

recipe/shopware.php

See: https://developer.shopware.com/docs/guides/plugins/plugins/framework/filesystem/filesystem.html

Feat: Update shopware recipe - add public/plugins to shared folders

---

contrib/ms-teams.php
docs/contrib/ms-teams.md

Since a Teams notification is not necessarily an essential part of a deploy, we should allow users to continue the deploy should a notification fail to send.
- [No] Bug fix #…?
- [Yes] New feature?
- [No] BC breaks?
- [Yes ] Tests added?
- [Yes] Docs added?

Allow Continue on Failure on Teams Notifications

---

recipe/symfony.php

The dump-env use correctly the current defined env in the `.env.local` file. While in maybe 99% the cases prod is the only envs there might be application having qa, stage, ... envs and in most cases the .env file is not parsed during deployer process, but flex correctly use the defined env from the .env.local file. So this is not needed and can even end in unexpected

Use current defined env in dump-env

---

recipe/provision/user.php

When the deployer user is provisioned, the SSH key file permissions are overwritten by the subsequent recursive chown command.
The permission modification has been moved inside the try/catch block after the recursive command.

fix: ssh key file permissions for provisioned user

---

docs/getting-started.md

This pull request makes a minor formatting correction in the documentation to improve readability. Specifically, it fixes the formatting of the file names in the deployment recipe section.
* Fixed formatting in `docs/getting-started.md` by removing an unnecessary line break and correcting the emphasis for `deploy.php` and `deploy.yaml` file names.
Currently it’s formatted incorrectly:

Fix formatting in getting-started.md

---

docs/basics.md

This pull request improves the documentation in `docs/basics.md` by adding a helpful note on dynamic configuration syntax. The new section demonstrates how to create configuration options that depend on overridden values.

Enhance documentation with dynamic config example
